import type {CalendarGeoItem} from '@/lib/d1/repositories/calendarGeo';
import {markerModel} from './sacred-markers';

type Locale='ru'|'uk'|'en';
type Text=Record<Locale,string>;
export type SacredPlace={id:string;name:Text;type:'major_center'|'cathedral'|'monastery'|'pilgrimage'|'event'|'saint_place';denomination:'orthodox'|'catholic'|'shared';lat:number;lng:number;country:string;description:Text;relatedSaints?:Text[];markerType:'king'|'queen'|'bishop'|'knight'|'rook'|'pawn';importance:number;source:string};
const names=(ru:string,uk:string,en:string):Text=>({ru,uk,en});
const unesco=(id:number)=>`https://whc.unesco.org/en/list/${id}/`;
// Small editorial starter catalog, never written to D1. Coordinates are map anchors,
// not surveyed building entrances. Marker roles express atlas hierarchy, not doctrine.
export const christianPlaces:SacredPlace[]=[
 {id:'jerusalem',name:names('Иерусалим','Єрусалим','Jerusalem'),type:'major_center',denomination:'shared',lat:31.7784,lng:35.2296,country:'IL / PS',markerType:'king',importance:100,description:names('Старый город и храм Гроба Господня — центр христианского паломничества.','Старе місто й храм Гробу Господнього — центр християнського паломництва.','The Old City and Church of the Holy Sepulchre are central Christian pilgrimage sites.'),source:unesco(148)},
 {id:'bethlehem',name:names('Вифлеем','Вифлеєм','Bethlehem'),type:'pilgrimage',denomination:'shared',lat:31.7043,lng:35.2075,country:'PS',markerType:'queen',importance:95,description:names('Храм Рождества стоит на месте, почитаемом христианами как место рождения Иисуса.','Храм Різдва стоїть на місці, яке християни шанують як місце народження Ісуса.','The Church of the Nativity marks the traditional birthplace of Jesus.'),source:unesco(1433)},
 {id:'nazareth',name:names('Назарет','Назарет','Nazareth'),type:'pilgrimage',denomination:'shared',lat:32.7022,lng:35.2978,country:'IL',markerType:'queen',importance:90,description:names('Город евангельского Благовещения и детства Иисуса.','Місто євангельського Благовіщення та дитинства Ісуса.','A city associated with the Annunciation and the childhood of Jesus.'),source:'https://www.custodia.org/en/sanctuaries/nazareth'},
 {id:'rome',name:names('Рим','Рим','Rome'),type:'major_center',denomination:'shared',lat:41.9028,lng:12.4964,country:'IT',markerType:'king',importance:100,description:names('Древний центр христианства с апостольскими базиликами и катакомбами.','Давній центр християнства з апостольськими базиліками та катакомбами.','An ancient Christian center with apostolic basilicas and catacombs.'),source:unesco(91)},
 {id:'vatican',name:names('Ватикан','Ватикан','Vatican'),type:'major_center',denomination:'catholic',lat:41.9022,lng:12.4539,country:'VA',markerType:'queen',importance:96,relatedSaints:[names('Апостол Пётр','Апостол Петро','Apostle Peter')],description:names('Собор Святого Петра — важнейшее место католического паломничества.','Собор Святого Петра — важливе місце католицького паломництва.','Saint Peter’s Basilica is a major Catholic pilgrimage destination.'),source:unesco(286)},
 {id:'constantinople',name:names('Константинополь / Стамбул','Константинополь / Стамбул','Constantinople / Istanbul'),type:'major_center',denomination:'shared',lat:41.0086,lng:28.9802,country:'TR',markerType:'king',importance:100,description:names('Историческая столица Византии; Святая София — памятник её христианского наследия.','Історична столиця Візантії; Свята Софія — пам’ятка її християнської спадщини.','The historic Byzantine capital; Hagia Sophia reflects its Christian heritage.'),source:unesco(356)},
 {id:'antioch',name:names('Антиохия / Антакья','Антіохія / Антак’я','Antioch / Antakya'),type:'saint_place',denomination:'shared',lat:36.2021,lng:36.1606,country:'TR',markerType:'pawn',importance:84,description:names('Один из ранних центров распространения христианства.','Один із ранніх центрів поширення християнства.','One of the early centers of Christianity.'),source:'https://en.wikipedia.org/wiki/Antioch'},
 {id:'alexandria',name:names('Александрия','Александрія','Alexandria'),type:'major_center',denomination:'shared',lat:31.2001,lng:29.9187,country:'EG',markerType:'bishop',importance:92,description:names('Древний патриарший центр и город раннехристианской богословской традиции.','Давній патріарший центр і місто ранньохристиянської богословської традиції.','An ancient patriarchal center with an early Christian theological tradition.'),source:'https://en.wikipedia.org/wiki/Christianity_in_Alexandria'},
 {id:'athos',name:names('Святая гора Афон','Свята гора Афон','Mount Athos'),type:'monastery',denomination:'orthodox',lat:40.257,lng:24.244,country:'GR',markerType:'rook',importance:95,description:names('Православный монашеский центр на Афонском полуострове.','Православний чернечий центр на Афонському півострові.','An Orthodox monastic center on the Athos peninsula.'),source:unesco(454)},
 {id:'kyiv',name:names('Киев','Київ','Kyiv'),type:'monastery',denomination:'orthodox',lat:50.4346,lng:30.5573,country:'UA',markerType:'rook',importance:93,description:names('Киево-Печерская лавра — исторический монастырский комплекс Киева.','Києво-Печерська лавра — історичний монастирський комплекс Києва.','Kyiv-Pechersk Lavra is a historic monastic complex in Kyiv.'),source:unesco(527)},
 {id:'moscow',name:names('Москва','Москва','Moscow'),type:'cathedral',denomination:'orthodox',lat:55.7505,lng:37.6175,country:'RU',markerType:'bishop',importance:88,description:names('Соборная площадь Кремля объединяет исторические православные соборы.','Соборна площа Кремля об’єднує історичні православні собори.','The Kremlin’s Cathedral Square contains historic Orthodox cathedrals.'),source:unesco(545)},
 {id:'sinai',name:names('Синай / Святая Екатерина','Синай / Свята Катерина','Sinai / Saint Catherine'),type:'monastery',denomination:'orthodox',lat:28.5559,lng:33.975,country:'EG',markerType:'rook',importance:94,description:names('Монастырь Святой Екатерины у подножия Синайских гор.','Монастир Святої Катерини біля підніжжя Синайських гір.','Saint Catherine’s Monastery stands at the foot of the Sinai mountains.'),source:unesco(954)},
 {id:'ephesus',name:names('Эфес','Ефес','Ephesus'),type:'event',denomination:'shared',lat:37.9411,lng:27.342,country:'TR',markerType:'knight',importance:85,description:names('Античный город с памятниками раннего христианства.','Античне місто з пам’ятками раннього християнства.','An ancient city preserving monuments of early Christianity.'),source:unesco(1018)},
 {id:'patmos',name:names('Патмос','Патмос','Patmos'),type:'monastery',denomination:'orthodox',lat:37.3092,lng:26.547,country:'GR',markerType:'rook',importance:86,relatedSaints:[names('Иоанн Богослов','Іоанн Богослов','John the Theologian')],description:names('Монастырь Иоанна Богослова и пещера Апокалипсиса.','Монастир Іоанна Богослова та печера Апокаліпсиса.','The Monastery of Saint John the Theologian and Cave of the Apocalypse.'),source:unesco(942)},
 {id:'ravenna',name:names('Равенна','Равенна','Ravenna'),type:'cathedral',denomination:'shared',lat:44.4207,lng:12.1966,country:'IT',markerType:'bishop',importance:80,description:names('Раннехристианские храмы, известные своими мозаиками.','Ранньохристиянські храми, відомі своїми мозаїками.','Early Christian churches renowned for their mosaics.'),source:unesco(788)},
 {id:'assisi',name:names('Ассизи','Ассізі','Assisi'),type:'saint_place',denomination:'catholic',lat:43.0759,lng:12.6055,country:'IT',markerType:'pawn',importance:82,relatedSaints:[names('Франциск Ассизский','Франциск Ассізький','Francis of Assisi')],description:names('Город Святого Франциска и францисканских памятников.','Місто Святого Франциска та францисканських пам’яток.','The city of Saint Francis and Franciscan monuments.'),source:unesco(990)},
 {id:'santiago',name:names('Сантьяго-де-Компостела','Сантьяго-де-Компостела','Santiago de Compostela'),type:'pilgrimage',denomination:'catholic',lat:42.8806,lng:-8.5446,country:'ES',markerType:'knight',importance:90,description:names('Собор и город назначения паломнических путей Святого Иакова.','Собор і місто призначення паломницьких шляхів Святого Якова.','The cathedral city at the destination of the Ways of Saint James.'),source:unesco(347)},
 {id:'lourdes',name:names('Лурд','Лурд','Lourdes'),type:'pilgrimage',denomination:'catholic',lat:43.0977,lng:-.0585,country:'FR',markerType:'queen',importance:83,description:names('Католическое святилище Богоматери и место паломничества.','Католицька святиня Богородиці та місце паломництва.','A Catholic Marian sanctuary and pilgrimage destination.'),source:'https://www.lourdes-france.com/en/'},
 {id:'fatima',name:names('Фатима','Фатіма','Fatima'),type:'pilgrimage',denomination:'catholic',lat:39.6324,lng:-8.6718,country:'PT',markerType:'queen',importance:83,description:names('Португальское католическое святилище Богоматери.','Португальська католицька святиня Богородиці.','A Catholic Marian sanctuary in Portugal.'),source:'https://www.fatima.pt/en/'},
 {id:'czestochowa',name:names('Ченстохова','Ченстохова','Częstochowa'),type:'monastery',denomination:'catholic',lat:50.8123,lng:19.0974,country:'PL',markerType:'rook',importance:85,description:names('Монастырь Ясная Гора и почитаемая Ченстоховская икона Богоматери.','Монастир Ясна Гора та шанована Ченстоховська ікона Богородиці.','Jasna Góra monastery and its venerated icon of Our Lady.'),source:'https://en.wikipedia.org/wiki/Jasna_G%C3%B3ra_Monastery'},
];
const roles={king:'major_sacred_place',queen:'icon',bishop:'monastery',knight:'pilgrimage_route',rook:'church',pawn:'saint'} as const;
export const chessModel=(role:SacredPlace['markerType'])=>markerModel(roles[role]);
export function sacredPlaceItem(place:SacredPlace,locale:Locale):CalendarGeoItem {
 return {entityId:`place:${place.id}`,entityType:place.type,title:place.name[locale],placeId:place.id,placeTitle:place.name[locale],lat:place.lat,lon:place.lng,relationType:'historical_place',markerPriority:place.importance,thumbnail:null,matchStatus:'editorial_demo'};
}
export function chessIcon(role:SacredPlace['markerType'],selected:boolean){
 const paths={king:'M22 43h20M25 39l-3-17 7 5 3-7 3 7 7-5-3 17M32 9v11M27 14h10',queen:'M23 40h18L38 28l5-12-11 7-11-7 5 12z',bishop:'M24 42h16l-4-14 5-7-9-12-9 12 5 7zM32 13v12',knight:'M23 42h20l-2-21-9-12-2 8-10 9 4 7 8-7-5 16z',rook:'M23 42h18l-3-18 5-4V11h-6v6h-5v-6h-5v6h-6v7l5 1z',pawn:'M24 42h16l-5-16h-6zM38 18a6 6 0 1 0-12 0 6 6 0 0 0 12 0'};
 return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 64 64"><circle cx="32" cy="30" r="27" fill="#101a24" stroke="${selected?'#ffe5a0':'#d6b474'}" stroke-width="2"/><path d="${paths[role]}" fill="none" stroke="#f6eedb" stroke-width="2.5" stroke-linejoin="round"/><path d="M27 57l5 6 5-6" fill="#d6b474"/></svg>`);
}
export const christianCopy={
 ru:{christianPlaces:'Христианские места',sacredModels:'Шахматные 3D-маркеры',related:'Связанные святые',major_center:'Духовный центр',cathedral:'Соборный центр',monastery:'Монастырь',pilgrimage:'Паломничество',event:'Историческое место',saint_place:'Место святого',orthodox:'Православие',catholic:'Католицизм',shared:'Общее христианское наследие'},
 uk:{christianPlaces:'Християнські місця',sacredModels:'Шахові 3D-маркери',related:'Пов’язані святі',major_center:'Духовний центр',cathedral:'Соборний центр',monastery:'Монастир',pilgrimage:'Паломництво',event:'Історичне місце',saint_place:'Місце святого',orthodox:'Православ’я',catholic:'Католицизм',shared:'Спільна християнська спадщина'},
 en:{christianPlaces:'Christian Places',sacredModels:'Sacred Chess Markers',related:'Related saints',major_center:'Spiritual center',cathedral:'Cathedral center',monastery:'Monastery',pilgrimage:'Pilgrimage',event:'Historic place',saint_place:'Saint’s place',orthodox:'Orthodox',catholic:'Catholic',shared:'Shared Christian heritage'},
};
