#!/usr/bin/env node
// Reads ./export/<table>.jsonl (written by export-from-postgres.mjs) and
// generates ./import-sql/<NN>_<table>.sql — batched INSERT statements ready
// for `wrangler d1 execute svetikony-production --local --file=...`.
//
// This script only WRITES .sql files to disk. It never calls wrangler and
// never touches any database itself — running it is safe at any time and
// produces nothing that affects local or remote D1 until those .sql files
// are explicitly applied by hand.
//
//   node scripts/d1-migration/import-to-d1.mjs
//
// Row count per generated file is logged so it can be diff'ed against the
// Postgres export counts before anything is applied.

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { TABLES } from './tables.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EXPORT_DIR = path.join(__dirname, 'export');
const IMPORT_DIR = path.join(__dirname, 'import-sql');
const BATCH_SIZE = 15; // matches the batch size validated against D1's SQLite
                        // parser for 0002_alphabet_seed.sql — larger batches
                        // risked "parser stack overflow" on deeply nested VALUES.

function sqlEscape(str) {
  return str.replace(/'/g, "''");
}

function formatValue(value, type) {
  if (value === null || value === undefined) return 'NULL';
  switch (type) {
    case 'bool':
      return value ? '1' : '0';
    case 'int':
      return String(value);
    case 'real':
      return String(value);
    case 'jsonb':
    case 'textarray':
      // value arrives already parsed (JSON.parse'd the outer jsonl line);
      // re-stringify compactly for storage as D1 TEXT.
      return `'${sqlEscape(JSON.stringify(value))}'`;
    case 'uuid':
    case 'text':
    case 'date':
    case 'timestamptz':
    default:
      return `'${sqlEscape(String(value))}'`;
  }
}

function buildInsertStatements(table, rows) {
  const columnNames = table.columns.map(([name]) => name).join(', ');
  const statements = [];
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const valuesSql = batch
      .map((row) => {
        const rendered = table.columns.map(([name, type]) => formatValue(row[name], type));
        return `(${rendered.join(', ')})`;
      })
      .join(',\n    ');
    statements.push(
      `INSERT INTO ${table.name} (${columnNames})\nVALUES\n    ${valuesSql}\nON CONFLICT DO NOTHING;`
    );
  }
  return statements;
}

function importTable(table) {
  const exportPath = path.join(EXPORT_DIR, `${table.name}.jsonl`);
  if (!existsSync(exportPath)) {
    console.warn(`skip ${table.name}: no export file at ${path.relative(process.cwd(), exportPath)} (run export-from-postgres.mjs first)`);
    return;
  }
  const lines = readFileSync(exportPath, 'utf8').split('\n').filter((l) => l.trim() !== '');
  const rows = lines.map((l) => JSON.parse(l));
  const statements = buildInsertStatements(table, rows);

  const header = `-- Generated by scripts/d1-migration/import-to-d1.mjs — DO NOT hand-edit,\n-- regenerate instead. Source: export/${table.name}.jsonl (${rows.length} rows).\n\n`;
  const outPath = path.join(IMPORT_DIR, `${String(table.order).padStart(2, '0')}_${table.name}.sql`);
  writeFileSync(outPath, header + statements.join('\n\n') + '\n');
  console.log(`${table.name.padEnd(32)} ${String(rows.length).padStart(6)} rows -> ${path.relative(process.cwd(), outPath)}`);
}

function buildCounterUpdate() {
  const seqPath = path.join(EXPORT_DIR, 'icon_order_number_seq.txt');
  if (!existsSync(seqPath)) {
    console.warn('skip icon_order_counters: no export/icon_order_number_seq.txt (run export-from-postgres.mjs first)');
    return;
  }
  const lastValue = readFileSync(seqPath, 'utf8').trim();
  if (!/^\d+$/.test(lastValue)) {
    throw new Error(`unexpected icon_order_number_seq value: ${lastValue}`);
  }
  const sql =
    `-- Aligns D1's order-number counter with the highest number Postgres\n` +
    `-- already issued (nextval('icon_order_number_seq') = ${lastValue} at export time),\n` +
    `-- so the first order placed after cutover doesn't collide with history.\n` +
    `-- Run this LAST, after 09_icon_orders.sql, and only once — re-running it\n` +
    `-- would reset the counter backwards if new D1 orders exist by then.\n\n` +
    `UPDATE icon_order_counters SET next_value = ${lastValue} WHERE id = 1;\n`;
  const outPath = path.join(IMPORT_DIR, '99_icon_order_counters.sql');
  writeFileSync(outPath, sql);
  console.log(`${'icon_order_counters'.padEnd(32)} ${'(seq)'.padStart(6)} rows -> ${path.relative(process.cwd(), outPath)}`);
}

function main() {
  mkdirSync(IMPORT_DIR, { recursive: true });
  for (const table of [...TABLES].sort((a, b) => a.order - b.order)) {
    importTable(table);
  }
  buildCounterUpdate();
}

main();
