// Shared table/column map for the Postgres -> D1 svetikony data migration.
// Single source of truth for both export-from-postgres.mjs and
// import-to-d1.mjs, so the two scripts can never drift out of sync with
// each other about column order or types.
//
// Column type markers (drive both the Postgres-side export projection and
// the D1-side INSERT value formatting):
//   'uuid'       passthrough string, unchanged
//   'text'       passthrough string, SQL-escaped on import
//   'int'        passthrough integer (covers Postgres INTEGER and BIGINT —
//                D1/SQLite INTEGER is already 8-byte, no separate BIGINT)
//   'real'       passthrough float
//   'bool'       Postgres boolean -> D1 0/1
//   'timestamptz' exported as UTC 'YYYY-MM-DDTHH:MI:SS.MSZ' text (matches the
//                 `strftime('%Y-%m-%dT%H:%M:%fZ','now')` convention already
//                 used for defaults in 0001_svetikony_schema.sql)
//   'date'       exported as 'YYYY-MM-DD' text
//   'jsonb'      passthrough JSON, re-stringified as compact text
//   'textarray'  Postgres TEXT[] -> JSON array text (same encoding as jsonb)
//
// `order` is the FK-safe import sequence (see MIGRATION_PLAN.md). Export can
// run in any order; import must not.

export const SITE_ID = '00000000-0000-0000-0000-000000000101';
const SITE_OR_GLOBAL = `(site_id = '${SITE_ID}' OR is_global = true)`;
const SITE_ONLY = `site_id = '${SITE_ID}'`;

export const TABLES = [
  {
    name: 'church_calendar_days',
    order: 1,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['date_old_style', 'date'],
      ['date_new_style', 'date'],
      ['calendar_type', 'text'],
      ['title', 'text'],
      ['day_type', 'text'],
      ['description', 'text'],
      ['rank', 'int'],
      ['status', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'icon_product_categories',
    order: 2,
    filter: SITE_ONLY,
    columns: [
      ['id', 'uuid'],
      ['slug', 'text'],
      ['name_uk', 'text'],
      ['name_ru', 'text'],
      ['name_en', 'text'],
      ['description_uk', 'text'],
      ['description_ru', 'text'],
      ['description_en', 'text'],
      ['image_url', 'text'],
      ['is_active', 'bool'],
      ['sort_order', 'int'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_icons',
    order: 3,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['calendar_day_id', 'uuid'],
      ['title', 'text'],
      ['slug', 'text'],
      ['image_url', 'text'],
      ['saint_name', 'text'],
      ['feast_name', 'text'],
      ['description', 'text'],
      ['language', 'text'],
      ['status', 'text'],
      ['translation_group_id', 'uuid'],
      ['order_enabled', 'bool'],
      ['order_block_text', 'text'],
      ['production_time', 'text'],
      ['price_cents', 'int'],
      ['currency', 'text'],
      ['consecration_available', 'bool'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'icon_order_options',
    order: 4,
    filter: SITE_ONLY,
    columns: [
      ['id', 'uuid'],
      ['slug', 'text'],
      ['name_uk', 'text'],
      ['name_ru', 'text'],
      ['name_en', 'text'],
      ['photo_url', 'text'],
      ['price_cents', 'int'],
      ['currency', 'text'],
      ['is_active', 'bool'],
      ['sort_order', 'int'],
      ['category_id', 'uuid'],
      ['description', 'text'],
      ['linked_icon_translation_group_id', 'uuid'],
      ['full_description_uk', 'text'],
      ['full_description_ru', 'text'],
      ['full_description_en', 'text'],
      ['gallery_urls', 'textarray'],
      ['production_time', 'text'],
      ['consecration_available', 'bool'],
      ['stock_status', 'text'],
      ['featured', 'bool'],
      ['seo_title_uk', 'text'],
      ['seo_title_ru', 'text'],
      ['seo_title_en', 'text'],
      ['seo_description_uk', 'text'],
      ['seo_description_ru', 'text'],
      ['seo_description_en', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_prayers',
    order: 5,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['icon_id', 'uuid'],
      ['calendar_day_id', 'uuid'],
      ['slug', 'text'],
      ['title', 'text'],
      ['text', 'text'],
      ['audio_url', 'text'],
      ['qr_code_url', 'text'],
      ['image_url', 'text'],
      ['source', 'text'],
      ['source_url', 'text'],
      ['note', 'text'],
      ['language', 'text'],
      ['prayer_type', 'text'],
      ['status', 'text'],
      ['translation_group_id', 'uuid'],
      ['visualizer_enabled', 'bool'],
      ['visualizer_image_url', 'text'],
      ['particle_count_desktop', 'int'],
      ['particle_count_mobile', 'int'],
      ['particle_size', 'real'],
      ['particle_color_mode', 'text'],
      ['background_color', 'text'],
      ['audio_reactivity', 'real'],
      ['scene_timeline', 'jsonb'],
      ['subtitle_cues', 'jsonb'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_articles',
    order: 6,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['icon_id', 'uuid'],
      ['calendar_day_id', 'uuid'],
      ['title', 'text'],
      ['slug', 'text'],
      ['content', 'text'],
      ['language', 'text'],
      ['seo_title', 'text'],
      ['seo_description', 'text'],
      ['status', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_gospel_readings',
    order: 7,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['icon_id', 'uuid'],
      ['calendar_day_id', 'uuid'],
      ['slug', 'text'],
      ['title', 'text'],
      ['reference', 'text'],
      ['text', 'text'],
      ['explanation', 'text'],
      ['language', 'text'],
      ['status', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_saints',
    order: 8,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['icon_id', 'uuid'],
      ['calendar_day_id', 'uuid'],
      ['slug', 'text'],
      ['name', 'text'],
      ['short_description', 'text'],
      ['biography', 'text'],
      ['feast_day', 'text'],
      ['image_url', 'text'],
      ['language', 'text'],
      ['translation_group_id', 'uuid'],
      ['status', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'icon_orders',
    order: 9,
    filter: SITE_OR_GLOBAL,
    columns: [
      ['id', 'uuid'],
      ['order_number', 'text'],
      ['icon_id', 'uuid'],
      ['icon_title_snapshot', 'text'],
      ['icon_slug_snapshot', 'text'],
      ['customer_name', 'text'],
      ['contact_method', 'text'],
      ['contact_value', 'text'],
      ['preferred_contact_channel', 'text'],
      ['country', 'text'],
      ['city', 'text'],
      ['consecration_requested', 'bool'],
      ['comment', 'text'],
      ['consent_given', 'bool'],
      ['status', 'text'],
      ['admin_note', 'text'],
      ['total_price_cents', 'int'],
      ['currency', 'text'],
      ['is_read', 'bool'],
      ['client_ip', 'text'],
      ['primary_product_id', 'uuid'],
      ['primary_product_name_snapshot', 'text'],
      ['primary_product_slug_snapshot', 'text'],
      ['primary_product_price_cents_snapshot', 'int'],
      ['primary_product_photo_snapshot', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'icon_order_items',
    order: 10,
    // no site_id of its own — scoped transitively through the parent order
    filter: `order_id IN (SELECT id FROM icon_orders WHERE ${SITE_OR_GLOBAL})`,
    columns: [
      ['id', 'uuid'],
      ['order_id', 'uuid'],
      ['option_id', 'uuid'],
      ['option_name_snapshot', 'text'],
      ['price_cents_snapshot', 'int'],
      ['quantity', 'int'],
      ['created_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_prayer_visualizer_assets',
    order: 11,
    // no site_id of its own — scoped transitively through the parent prayer
    filter: `prayer_id IN (SELECT id FROM church_prayers WHERE ${SITE_OR_GLOBAL})`,
    columns: [
      ['id', 'uuid'],
      ['prayer_id', 'uuid'],
      ['source_image_url', 'text'],
      ['desktop_map_url', 'text'],
      ['mobile_map_url', 'text'],
      ['low_power_map_url', 'text'],
      ['fallback_image_url', 'text'],
      ['thumbnail_url', 'text'],
      ['desktop_particle_count', 'int'],
      ['mobile_particle_count', 'int'],
      ['low_power_particle_count', 'int'],
      ['processing_status', 'text'],
      ['processing_error', 'text'],
      ['processing_version', 'int'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'church_info',
    order: 12,
    filter: SITE_ONLY,
    columns: [
      ['id', 'uuid'],
      ['address', 'text'],
      ['maps_url', 'text'],
      ['phone_or_site', 'text'],
      ['priest_phone', 'text'],
      ['image_url', 'text'],
      ['translations', 'jsonb'],
      ['gallery_images', 'textarray'],
      ['status', 'text'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  // church_alphabet_letters is intentionally NOT listed here — it was
  // already seeded into D1 by 0002_alphabet_seed.sql, transcribed straight
  // from the migration file rather than from live data. See
  // MIGRATION_PLAN.md "church_alphabet_letters" section before deciding
  // whether to re-import it from Postgres (their row ids will NOT match).
];
