-- =============================================================================
-- svetikony — D1 seed data: Old Slavonic alphabet (46 letters x uk/ru/en)
-- =============================================================================
-- Ported from ../../assistant/migrations/20260715000001_church_alphabet.sql
-- (seed content only — the table/indexes/trigger come from
-- 0001_svetikony_schema.sql). Content of every letter is untouched; only the
-- SQL shape changed:
--   - dropped the `site_id` column/value (this D1 database is svetikony-only)
--   - dropped the `is_global` column/value (no other site to be global across)
--   - the original used one `WITH grouped AS (...)` CTE + a single 138-row
--     INSERT so all 3 language rows of a letter could share one
--     gen_random_uuid() via a subselect. Trying that same shape verbatim in
--     SQLite hit "parser stack overflow" (D1's SQLite parser has a much
--     lower recursion limit than Postgres for deeply-nested VALUES/CTEs).
--     Fix: the 46 translation-group UUIDs are pre-generated below as literal
--     values (no CTE, no subselect), and the INSERT is batched into 15-row
--     statements — both changes are purely mechanical, no data changed.
-- =============================================================================

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('az', 'А', 1, 'Азъ', 'Я, початок, людина', 'Азъ — знак старословʼянської азбуки. Його сенс: Я, початок, людина. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'А', '#9a2b1e', '', '', '', '', 'uk', '08123a57-f25f-4983-8d22-0086989d97ae', 'published'),
    ('az', 'А', 1, 'Азъ', 'Я, начало, человек', 'Азъ напоминает, что познание начинается с личности и ответственности человека перед Богом, словом и делом.', NULL, 'А', '#9a2b1e', '', '', '', '', 'ru', '08123a57-f25f-4983-8d22-0086989d97ae', 'published'),
    ('az', 'А', 1, 'Азъ', 'I, beginning, person', 'Азъ is a sign of the Old Slavonic alphabet. Its meaning: I, beginning, person. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'А', '#9a2b1e', '', '', '', '', 'en', '08123a57-f25f-4983-8d22-0086989d97ae', 'published'),
    ('buki', 'Б', 2, 'Буки', 'Літери, знання, письмо', 'Буки — знак старословʼянської азбуки. Його сенс: Літери, знання, письмо. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Б', '#1f3f66', '', '', '', '', 'uk', '16ee06e3-456d-4d47-bd56-c6bff0cfc83b', 'published'),
    ('buki', 'Б', 2, 'Буки', 'Буквы, знание, письмо', 'Буки открывает путь к письменной памяти: через буквы сохранялись молитвы, книги и церковное предание.', NULL, 'Б', '#1f3f66', '', '', '', '', 'ru', '16ee06e3-456d-4d47-bd56-c6bff0cfc83b', 'published'),
    ('buki', 'Б', 2, 'Буки', 'Letters, knowledge, writing', 'Буки is a sign of the Old Slavonic alphabet. Its meaning: Letters, knowledge, writing. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Б', '#1f3f66', '', '', '', '', 'en', '16ee06e3-456d-4d47-bd56-c6bff0cfc83b', 'published'),
    ('vedi', 'В', 3, 'Веди', 'Відаю, знаю', 'Веди — знак старословʼянської азбуки. Його сенс: Відаю, знаю. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'В', '#9a2b1e', '', '', '', '', 'uk', '3f879cc6-1a5c-449e-bcfc-b9cb915502b5', 'published'),
    ('vedi', 'В', 3, 'Веди', 'Ведаю, знаю', 'Веди говорит о знании не как о гордости, а как о внимательном ведении истины и смысла.', NULL, 'В', '#9a2b1e', '', '', '', '', 'ru', '3f879cc6-1a5c-449e-bcfc-b9cb915502b5', 'published'),
    ('vedi', 'В', 3, 'Веди', 'I know, I understand', 'Веди is a sign of the Old Slavonic alphabet. Its meaning: I know, I understand. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'В', '#9a2b1e', '', '', '', '', 'en', '3f879cc6-1a5c-449e-bcfc-b9cb915502b5', 'published'),
    ('glagoli', 'Г', 4, 'Глаголи', 'Говори, слово, мовлення', 'Глаголи — знак старословʼянської азбуки. Його сенс: Говори, слово, мовлення. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Г', '#1f3f66', '', '', '', '', 'uk', '03d8f89c-6ab0-4b84-895a-49ead247e228', 'published'),
    ('glagoli', 'Г', 4, 'Глаголи', 'Говори, слово, речь', 'Глаголи напоминает: слово должно быть живым, правдивым и добрым, потому что речь формирует сердце.', NULL, 'Г', '#1f3f66', '', '', '', '', 'ru', '03d8f89c-6ab0-4b84-895a-49ead247e228', 'published'),
    ('glagoli', 'Г', 4, 'Глаголи', 'Speak, word, speech', 'Глаголи is a sign of the Old Slavonic alphabet. Its meaning: Speak, word, speech. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Г', '#1f3f66', '', '', '', '', 'en', '03d8f89c-6ab0-4b84-895a-49ead247e228', 'published'),
    ('dobro', 'Д', 5, 'Добро', 'Добро, благо, добра справа', 'Добро — знак старословʼянської азбуки. Його сенс: Добро, благо, добра справа. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Д', '#9a2b1e', '', '', '', '', 'uk', '65c510a5-3ba3-4b8b-bed0-dc9f3875a189', 'published'),
    ('dobro', 'Д', 5, 'Добро', 'Добро, благо, доброе дело', 'Добро соединяет знание и поступок: истинное слово должно вести к милосердию и благому делу.', NULL, 'Д', '#9a2b1e', '', '', '', '', 'ru', '65c510a5-3ba3-4b8b-bed0-dc9f3875a189', 'published'),
    ('dobro', 'Д', 5, 'Добро', 'Goodness, blessing, good deed', 'Добро is a sign of the Old Slavonic alphabet. Its meaning: Goodness, blessing, good deed. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Д', '#9a2b1e', '', '', '', '', 'en', '65c510a5-3ba3-4b8b-bed0-dc9f3875a189', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('est', 'Є', 6, 'Есть', 'Є, існує, буття', 'Есть — знак старословʼянської азбуки. Його сенс: Є, існує, буття. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Е / Є', '#1f3f66', '', '', '', '', 'uk', '50eadc97-c06e-47a8-a63d-c7f53bdf1e0a', 'published'),
    ('est', 'Є', 6, 'Есть', 'Есть, существует, бытие', 'Есть указывает на бытие и присутствие: добро не только произносится, но существует и становится жизнью.', NULL, 'Е / Є', '#1f3f66', '', '', '', '', 'ru', '50eadc97-c06e-47a8-a63d-c7f53bdf1e0a', 'published'),
    ('est', 'Є', 6, 'Есть', 'Is, exists, being', 'Есть is a sign of the Old Slavonic alphabet. Its meaning: Is, exists, being. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Е / Є', '#1f3f66', '', '', '', '', 'en', '50eadc97-c06e-47a8-a63d-c7f53bdf1e0a', 'published'),
    ('zhivete', 'Ж', 7, 'Живете', 'Життя, живіть', 'Живете — знак старословʼянської азбуки. Його сенс: Життя, живіть. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ж', '#9a2b1e', '', '', '', '', 'uk', 'ca205573-4d1b-4e3f-9b94-718117dcbc10', 'published'),
    ('zhivete', 'Ж', 7, 'Живете', 'Жизнь, живите', 'Живете звучит как призыв жить осмысленно, хранить душу и принимать жизнь как дар.', NULL, 'Ж', '#9a2b1e', '', '', '', '', 'ru', 'ca205573-4d1b-4e3f-9b94-718117dcbc10', 'published'),
    ('zhivete', 'Ж', 7, 'Живете', 'Life, live', 'Живете is a sign of the Old Slavonic alphabet. Its meaning: Life, live. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ж', '#9a2b1e', '', '', '', '', 'en', 'ca205573-4d1b-4e3f-9b94-718117dcbc10', 'published'),
    ('dzelo', 'Ѕ', 8, 'Зело', 'Вельми, дуже', 'Зело — знак старословʼянської азбуки. Його сенс: Вельми, дуже. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ДЗ', '#1f3f66', '', '', '', '', 'uk', '7efa5d5f-26f9-4083-a7b0-66703e9d685a', 'published'),
    ('dzelo', 'Ѕ', 8, 'Зело', 'Весьма, очень', 'Зело передавало звук дз и усиливало смысл: в древней книжности даже редкие буквы помогали точнее слышать слово.', NULL, 'ДЗ', '#1f3f66', '', '', '', '', 'ru', '7efa5d5f-26f9-4083-a7b0-66703e9d685a', 'published'),
    ('dzelo', 'Ѕ', 8, 'Зело', 'Very, greatly', 'Зело is a sign of the Old Slavonic alphabet. Its meaning: Very, greatly. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ДЗ', '#1f3f66', '', '', '', '', 'en', '7efa5d5f-26f9-4083-a7b0-66703e9d685a', 'published'),
    ('zemlya', 'З', 9, 'Земля', 'Земля, світ', 'Земля — знак старословʼянської азбуки. Його сенс: Земля, світ. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'З', '#9a2b1e', '', '', '', '', 'uk', 'cbc36b37-b5b1-4180-abd1-c3960e4f8b16', 'published'),
    ('zemlya', 'З', 9, 'Земля', 'Земля, мир', 'Земля напоминает о мире, доме и творении, где человек призван трудиться и хранить порядок.', NULL, 'З', '#9a2b1e', '', '', '', '', 'ru', 'cbc36b37-b5b1-4180-abd1-c3960e4f8b16', 'published'),
    ('zemlya', 'З', 9, 'Земля', 'Earth, world', 'Земля is a sign of the Old Slavonic alphabet. Its meaning: Earth, world. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'З', '#9a2b1e', '', '', '', '', 'en', 'cbc36b37-b5b1-4180-abd1-c3960e4f8b16', 'published'),
    ('izhe', 'И', 10, 'Иже', 'Котрий, той', 'Иже — знак старословʼянської азбуки. Його сенс: Котрий, той. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'И', '#1f3f66', '', '', '', '', 'uk', 'c57c60c6-688b-46e0-b7d7-395d60fd9c0b', 'published'),
    ('izhe', 'И', 10, 'Иже', 'Который, тот', 'Иже связывает слова и смыслы, помогая древнему тексту звучать стройно и молитвенно.', NULL, 'И', '#1f3f66', '', '', '', '', 'ru', 'c57c60c6-688b-46e0-b7d7-395d60fd9c0b', 'published'),
    ('izhe', 'И', 10, 'Иже', 'Which, that one', 'Иже is a sign of the Old Slavonic alphabet. Its meaning: Which, that one. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'И', '#1f3f66', '', '', '', '', 'en', 'c57c60c6-688b-46e0-b7d7-395d60fd9c0b', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('i', 'І', 11, 'И', 'І, сполучник, рух звуку', 'И — знак старословʼянської азбуки. Його сенс: І, сполучник, рух звуку. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'И / Й', '#9a2b1e', '', '', '', '', 'uk', '84b7cba8-e8bd-4a8b-91e4-694816dd7e6b', 'published'),
    ('i', 'І', 11, 'И', 'И, союз, движение звука', 'Іота сохраняет греческую книжную память и показывает, как славянская азбука соединяла местную речь с церковной традицией.', NULL, 'И / Й', '#9a2b1e', '', '', '', '', 'ru', '84b7cba8-e8bd-4a8b-91e4-694816dd7e6b', 'published'),
    ('i', 'І', 11, 'И', 'And, conjunction, movement of sound', 'И is a sign of the Old Slavonic alphabet. Its meaning: And, conjunction, movement of sound. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'И / Й', '#9a2b1e', '', '', '', '', 'en', '84b7cba8-e8bd-4a8b-91e4-694816dd7e6b', 'published'),
    ('kako', 'К', 12, 'Како', 'Як, яким чином', 'Како — знак старословʼянської азбуки. Його сенс: Як, яким чином. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'К', '#1f3f66', '', '', '', '', 'uk', 'f8566e37-7195-4774-84b6-2857b63ab823', 'published'),
    ('kako', 'К', 12, 'Како', 'Как, каким образом', 'Како задает вопрос о пути: мало знать цель, важно понять, как идти к ней честно.', NULL, 'К', '#1f3f66', '', '', '', '', 'ru', 'f8566e37-7195-4774-84b6-2857b63ab823', 'published'),
    ('kako', 'К', 12, 'Како', 'How, in what way', 'Како is a sign of the Old Slavonic alphabet. Its meaning: How, in what way. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'К', '#1f3f66', '', '', '', '', 'en', 'f8566e37-7195-4774-84b6-2857b63ab823', 'published'),
    ('lyudi', 'Л', 13, 'Люди', 'Люди, народ', 'Люди — знак старословʼянської азбуки. Його сенс: Люди, народ. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Л', '#9a2b1e', '', '', '', '', 'uk', '05c8eabf-1ade-4b3b-bd2a-deb9a2562986', 'published'),
    ('lyudi', 'Л', 13, 'Люди', 'Люди, народ', 'Люди говорит о соборности: буквы и книги служили не одиночеству, а народу и общине.', NULL, 'Л', '#9a2b1e', '', '', '', '', 'ru', '05c8eabf-1ade-4b3b-bd2a-deb9a2562986', 'published'),
    ('lyudi', 'Л', 13, 'Люди', 'People, nation', 'Люди is a sign of the Old Slavonic alphabet. Its meaning: People, nation. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Л', '#9a2b1e', '', '', '', '', 'en', '05c8eabf-1ade-4b3b-bd2a-deb9a2562986', 'published'),
    ('myslete', 'М', 14, 'Мыслете', 'Мисліть, думайте', 'Мыслете — знак старословʼянської азбуки. Його сенс: Мисліть, думайте. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'М', '#1f3f66', '', '', '', '', 'uk', 'a4332624-39e7-4838-a8e7-a371831593cd', 'published'),
    ('myslete', 'М', 14, 'Мыслете', 'Мыслите, думайте', 'Мыслете призывает к рассуждению, вниманию и духовной трезвости в словах и поступках.', NULL, 'М', '#1f3f66', '', '', '', '', 'ru', 'a4332624-39e7-4838-a8e7-a371831593cd', 'published'),
    ('myslete', 'М', 14, 'Мыслете', 'Think, reflect', 'Мыслете is a sign of the Old Slavonic alphabet. Its meaning: Think, reflect. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'М', '#1f3f66', '', '', '', '', 'en', 'a4332624-39e7-4838-a8e7-a371831593cd', 'published'),
    ('nash', 'Н', 15, 'Нашъ', 'Наш', 'Нашъ — знак старословʼянської азбуки. Його сенс: Наш. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Н', '#9a2b1e', '', '', '', '', 'uk', '9e1fb3b7-641d-46d7-b2e8-efcea269cdf3', 'published'),
    ('nash', 'Н', 15, 'Нашъ', 'Наш', 'Нашъ хранит чувство принадлежности: вера, язык и память передаются как общее наследие.', NULL, 'Н', '#9a2b1e', '', '', '', '', 'ru', '9e1fb3b7-641d-46d7-b2e8-efcea269cdf3', 'published'),
    ('nash', 'Н', 15, 'Нашъ', 'Our', 'Нашъ is a sign of the Old Slavonic alphabet. Its meaning: Our. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Н', '#9a2b1e', '', '', '', '', 'en', '9e1fb3b7-641d-46d7-b2e8-efcea269cdf3', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('on', 'О', 16, 'Онъ', 'Він', 'Онъ — знак старословʼянської азбуки. Його сенс: Він. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'О', '#1f3f66', '', '', '', '', 'uk', '9b3afd59-5340-4da6-9461-0f13380634ad', 'published'),
    ('on', 'О', 16, 'Онъ', 'Он', 'Онъ обращает взгляд от себя к Другому, к ближнему и к Богу, перед Которым слово становится ответственным.', NULL, 'О', '#1f3f66', '', '', '', '', 'ru', '9b3afd59-5340-4da6-9461-0f13380634ad', 'published'),
    ('on', 'О', 16, 'Онъ', 'He', 'Онъ is a sign of the Old Slavonic alphabet. Its meaning: He. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'О', '#1f3f66', '', '', '', '', 'en', '9b3afd59-5340-4da6-9461-0f13380634ad', 'published'),
    ('pokoy', 'П', 17, 'Покой', 'Мир, спокій', 'Покой — знак старословʼянської азбуки. Його сенс: Мир, спокій. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'П', '#9a2b1e', '', '', '', '', 'uk', '2186d297-32d5-49bc-9e73-8819b4f920a1', 'published'),
    ('pokoy', 'П', 17, 'Покой', 'Мир, покой', 'Покой напоминает о внутреннем мире, который рождается из молитвы, правды и добрых дел.', NULL, 'П', '#9a2b1e', '', '', '', '', 'ru', '2186d297-32d5-49bc-9e73-8819b4f920a1', 'published'),
    ('pokoy', 'П', 17, 'Покой', 'Peace, rest', 'Покой is a sign of the Old Slavonic alphabet. Its meaning: Peace, rest. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'П', '#9a2b1e', '', '', '', '', 'en', '2186d297-32d5-49bc-9e73-8819b4f920a1', 'published'),
    ('rtsy', 'Р', 18, 'Рцы', 'Говори, промов', 'Рцы — знак старословʼянської азбуки. Його сенс: Говори, промов. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Р', '#1f3f66', '', '', '', '', 'uk', 'e5989758-afce-4273-ab5c-8b16e00d0b38', 'published'),
    ('rtsy', 'Р', 18, 'Рцы', 'Говори, изреки', 'Рцы снова возвращает к речи: произнесенное слово должно быть ясным и достойным.', NULL, 'Р', '#1f3f66', '', '', '', '', 'ru', 'e5989758-afce-4273-ab5c-8b16e00d0b38', 'published'),
    ('rtsy', 'Р', 18, 'Рцы', 'Speak, utter', 'Рцы is a sign of the Old Slavonic alphabet. Its meaning: Speak, utter. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Р', '#1f3f66', '', '', '', '', 'en', 'e5989758-afce-4273-ab5c-8b16e00d0b38', 'published'),
    ('slovo', 'С', 19, 'Слово', 'Слово', 'Слово — знак старословʼянської азбуки. Його сенс: Слово. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'С', '#9a2b1e', '', '', '', '', 'uk', 'a1219822-202d-4447-bb06-28bcf4552dbd', 'published'),
    ('slovo', 'С', 19, 'Слово', 'Слово', 'Слово в церковной культуре не просто звук: это смысл, молитва, свидетельство и память.', NULL, 'С', '#9a2b1e', '', '', '', '', 'ru', 'a1219822-202d-4447-bb06-28bcf4552dbd', 'published'),
    ('slovo', 'С', 19, 'Слово', 'Word', 'Слово is a sign of the Old Slavonic alphabet. Its meaning: Word. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'С', '#9a2b1e', '', '', '', '', 'en', 'a1219822-202d-4447-bb06-28bcf4552dbd', 'published'),
    ('tverdo', 'Т', 20, 'Твердо', 'Твердо, міцно', 'Твердо — знак старословʼянської азбуки. Його сенс: Твердо, міцно. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Т', '#1f3f66', '', '', '', '', 'uk', 'c179993c-a3c0-412a-b105-f3cfe9387a20', 'published'),
    ('tverdo', 'Т', 20, 'Твердо', 'Твердо, крепко', 'Твердо говорит о стойкости: доброе знание должно укореняться и выдерживать испытания.', NULL, 'Т', '#1f3f66', '', '', '', '', 'ru', 'c179993c-a3c0-412a-b105-f3cfe9387a20', 'published'),
    ('tverdo', 'Т', 20, 'Твердо', 'Firmly, strongly', 'Твердо is a sign of the Old Slavonic alphabet. Its meaning: Firmly, strongly. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Т', '#1f3f66', '', '', '', '', 'en', 'c179993c-a3c0-412a-b105-f3cfe9387a20', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('uk', 'Ꙋ', 21, 'Укъ', 'Учення, знання', 'Укъ — знак старословʼянської азбуки. Його сенс: Учення, знання. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'У', '#9a2b1e', '', '', '', '', 'uk', '04b3f292-7d73-4d59-8043-fedea7102c71', 'published'),
    ('uk', 'Ꙋ', 21, 'Укъ', 'Учение, знание', 'Укъ связан с учением: азбука была дорогой к книге, молитве и пониманию церковного текста.', NULL, 'У', '#9a2b1e', '', '', '', '', 'ru', '04b3f292-7d73-4d59-8043-fedea7102c71', 'published'),
    ('uk', 'Ꙋ', 21, 'Укъ', 'Teaching, knowledge', 'Укъ is a sign of the Old Slavonic alphabet. Its meaning: Teaching, knowledge. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'У', '#9a2b1e', '', '', '', '', 'en', '04b3f292-7d73-4d59-8043-fedea7102c71', 'published'),
    ('fert', 'Ф', 22, 'Фертъ', 'Літера Ф', 'Фертъ — знак старословʼянської азбуки. Його сенс: Літера Ф. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ф', '#1f3f66', '', '', '', '', 'uk', 'd4a07344-be25-43ec-a499-f42fddaa8868', 'published'),
    ('fert', 'Ф', 22, 'Фертъ', 'Буква Ф', 'Фертъ сохраняет особый звук и показывает, как азбука принимала разные пласты книжной традиции.', NULL, 'Ф', '#1f3f66', '', '', '', '', 'ru', 'd4a07344-be25-43ec-a499-f42fddaa8868', 'published'),
    ('fert', 'Ф', 22, 'Фертъ', 'The letter F', 'Фертъ is a sign of the Old Slavonic alphabet. Its meaning: The letter F. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ф', '#1f3f66', '', '', '', '', 'en', 'd4a07344-be25-43ec-a499-f42fddaa8868', 'published'),
    ('her', 'Х', 23, 'Херъ', 'Літера Х', 'Херъ — знак старословʼянської азбуки. Його сенс: Літера Х. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Х', '#9a2b1e', '', '', '', '', 'uk', '0094f24e-f1f4-4e27-ace7-5299c6534cc0', 'published'),
    ('her', 'Х', 23, 'Херъ', 'Буква Х', 'Херъ передает твердый дыхательный звук, часто встречающийся в греческих и церковных именах.', NULL, 'Х', '#9a2b1e', '', '', '', '', 'ru', '0094f24e-f1f4-4e27-ace7-5299c6534cc0', 'published'),
    ('her', 'Х', 23, 'Херъ', 'The letter Kh', 'Херъ is a sign of the Old Slavonic alphabet. Its meaning: The letter Kh. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Х', '#9a2b1e', '', '', '', '', 'en', '0094f24e-f1f4-4e27-ace7-5299c6534cc0', 'published'),
    ('omega', 'Ѡ', 24, 'Отъ', 'От, омега, урочисте О', 'Отъ — знак старословʼянської азбуки. Його сенс: От, омега, урочисте О. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'О / Омега', '#1f3f66', '', '', '', '', 'uk', 'a75d4c31-65d9-424c-a1ba-dcece1c77102', 'published'),
    ('omega', 'Ѡ', 24, 'Отъ', 'От, омега, торжественное О', 'Омега чаще встречалась в книжных и греческих словах, а также как декоративная торжественная буква.', NULL, 'О / Омега', '#1f3f66', '', '', '', '', 'ru', 'a75d4c31-65d9-424c-a1ba-dcece1c77102', 'published'),
    ('omega', 'Ѡ', 24, 'Отъ', 'Ot, omega, solemn O', 'Отъ is a sign of the Old Slavonic alphabet. Its meaning: Ot, omega, solemn O. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'О / Омега', '#1f3f66', '', '', '', '', 'en', 'a75d4c31-65d9-424c-a1ba-dcece1c77102', 'published'),
    ('tsy', 'Ц', 25, 'Цы', 'Літера Ц', 'Цы — знак старословʼянської азбуки. Його сенс: Літера Ц. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ц', '#9a2b1e', '', '', '', '', 'uk', '3b55b1e1-5668-4390-a51f-a8953d1755b3', 'published'),
    ('tsy', 'Ц', 25, 'Цы', 'Буква Ц', 'Цы хранит резкий ясный звук, важный для точного чтения древних слов и имен.', NULL, 'Ц', '#9a2b1e', '', '', '', '', 'ru', '3b55b1e1-5668-4390-a51f-a8953d1755b3', 'published'),
    ('tsy', 'Ц', 25, 'Цы', 'The letter Ts', 'Цы is a sign of the Old Slavonic alphabet. Its meaning: The letter Ts. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ц', '#9a2b1e', '', '', '', '', 'en', '3b55b1e1-5668-4390-a51f-a8953d1755b3', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('cherv', 'Ч', 26, 'Червь', 'Літера Ч', 'Червь — знак старословʼянської азбуки. Його сенс: Літера Ч. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ч', '#1f3f66', '', '', '', '', 'uk', 'bc30c796-6153-489c-963c-6136202b7c5b', 'published'),
    ('cherv', 'Ч', 26, 'Червь', 'Буква Ч', 'Червь напоминает, что даже непривычные названия букв были частью живой учебной традиции.', NULL, 'Ч', '#1f3f66', '', '', '', '', 'ru', 'bc30c796-6153-489c-963c-6136202b7c5b', 'published'),
    ('cherv', 'Ч', 26, 'Червь', 'The letter Ch', 'Червь is a sign of the Old Slavonic alphabet. Its meaning: The letter Ch. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ч', '#1f3f66', '', '', '', '', 'en', 'bc30c796-6153-489c-963c-6136202b7c5b', 'published'),
    ('sha', 'Ш', 27, 'Ша', 'Літера Ш', 'Ша — знак старословʼянської азбуки. Його сенс: Літера Ш. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ш', '#9a2b1e', '', '', '', '', 'uk', '0aee8420-55f4-4c14-999e-9c096a9d18ed', 'published'),
    ('sha', 'Ш', 27, 'Ша', 'Буква Ш', 'Ша дает мягкую широту звучания, знакомую славянской речи и церковному чтению.', NULL, 'Ш', '#9a2b1e', '', '', '', '', 'ru', '0aee8420-55f4-4c14-999e-9c096a9d18ed', 'published'),
    ('sha', 'Ш', 27, 'Ша', 'The letter Sh', 'Ша is a sign of the Old Slavonic alphabet. Its meaning: The letter Sh. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ш', '#9a2b1e', '', '', '', '', 'en', '0aee8420-55f4-4c14-999e-9c096a9d18ed', 'published'),
    ('shta', 'Щ', 28, 'Шта', 'Літера Щ, сполучення шт', 'Шта — знак старословʼянської азбуки. Його сенс: Літера Щ, сполучення шт. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Щ / ШТ', '#1f3f66', '', '', '', '', 'uk', '44e829f6-ab5d-4c91-b458-5017bef16e48', 'published'),
    ('shta', 'Щ', 28, 'Шта', 'Буква Щ, сочетание шт', 'Шта передает сложный славянский звук и показывает тонкость древней фонетики.', NULL, 'Щ / ШТ', '#1f3f66', '', '', '', '', 'ru', '44e829f6-ab5d-4c91-b458-5017bef16e48', 'published'),
    ('shta', 'Щ', 28, 'Шта', 'The letter Shch, the sht sound cluster', 'Шта is a sign of the Old Slavonic alphabet. Its meaning: The letter Shch, the sht sound cluster. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Щ / ШТ', '#1f3f66', '', '', '', '', 'en', '44e829f6-ab5d-4c91-b458-5017bef16e48', 'published'),
    ('er', 'Ъ', 29, 'Еръ', 'Твердий знак, давній редукований звук', 'Еръ — знак старословʼянської азбуки. Його сенс: Твердий знак, давній редукований звук. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Краткий твердый гласный', '#9a2b1e', '', '', '', '', 'uk', 'a09cdd65-f042-47a1-ba89-859175872426', 'published'),
    ('er', 'Ъ', 29, 'Еръ', 'Твердый знак, древний редуцированный звук', 'Еръ отмечал особенность звучания и письма, помогая древнему тексту сохранять ритм.', NULL, 'Краткий твердый гласный', '#9a2b1e', '', '', '', '', 'ru', 'a09cdd65-f042-47a1-ba89-859175872426', 'published'),
    ('er', 'Ъ', 29, 'Еръ', 'Hard sign, an old reduced vowel', 'Еръ is a sign of the Old Slavonic alphabet. Its meaning: Hard sign, an old reduced vowel. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Краткий твердый гласный', '#9a2b1e', '', '', '', '', 'en', 'a09cdd65-f042-47a1-ba89-859175872426', 'published'),
    ('yery', 'Ꙑ', 30, 'Еры', 'И', 'Еры — знак старословʼянської азбуки. Його сенс: И. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ы', '#1f3f66', '', '', '', '', 'uk', '05ce6b2b-4dff-4244-a328-6f804c8a9e12', 'published'),
    ('yery', 'Ꙑ', 30, 'Еры', 'Ы', 'Еры хранит характерный славянский звук, который отличает живую речь от книжной схемы.', NULL, 'Ы', '#1f3f66', '', '', '', '', 'ru', '05ce6b2b-4dff-4244-a328-6f804c8a9e12', 'published'),
    ('yery', 'Ꙑ', 30, 'Еры', 'Y sound', 'Еры is a sign of the Old Slavonic alphabet. Its meaning: Y sound. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ы', '#1f3f66', '', '', '', '', 'en', '05ce6b2b-4dff-4244-a328-6f804c8a9e12', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('er-soft', 'Ь', 31, 'Ерь', 'Мʼякий знак, давній редукований звук', 'Ерь — знак старословʼянської азбуки. Його сенс: Мʼякий знак, давній редукований звук. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Краткий мягкий гласный', '#9a2b1e', '', '', '', '', 'uk', '081b9d90-8adf-4f64-b429-c7b1f897c8e1', 'published'),
    ('er-soft', 'Ь', 31, 'Ерь', 'Мягкий знак, древний редуцированный звук', 'Ерь смягчает звучание и напоминает, что в письме важна не только буква, но и тонкость произношения.', NULL, 'Краткий мягкий гласный', '#9a2b1e', '', '', '', '', 'ru', '081b9d90-8adf-4f64-b429-c7b1f897c8e1', 'published'),
    ('er-soft', 'Ь', 31, 'Ерь', 'Soft sign, an old reduced vowel', 'Ерь is a sign of the Old Slavonic alphabet. Its meaning: Soft sign, an old reduced vowel. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Краткий мягкий гласный', '#9a2b1e', '', '', '', '', 'en', '081b9d90-8adf-4f64-b429-c7b1f897c8e1', 'published'),
    ('yat', 'Ѣ', 32, 'Ять', 'Давній звук ѣ', 'Ять — знак старословʼянської азбуки. Його сенс: Давній звук ѣ. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ѣ', '#1f3f66', '', '', '', '', 'uk', '588147c5-11ef-4b8e-bf53-05cade2eccb8', 'published'),
    ('yat', 'Ѣ', 32, 'Ять', 'Древний звук ѣ', 'Ять стала знаком древней книжности: ее история показывает, как менялся язык и сохранялась память.', NULL, 'Ѣ', '#1f3f66', '', '', '', '', 'ru', '588147c5-11ef-4b8e-bf53-05cade2eccb8', 'published'),
    ('yat', 'Ѣ', 32, 'Ять', 'Ancient yat sound', 'Ять is a sign of the Old Slavonic alphabet. Its meaning: Ancient yat sound. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ѣ', '#1f3f66', '', '', '', '', 'en', '588147c5-11ef-4b8e-bf53-05cade2eccb8', 'published'),
    ('ya-iotated', 'Ꙗ', 33, 'Я', 'Йотоване А', 'Я — знак старословʼянської азбуки. Його сенс: Йотоване А. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Я', '#9a2b1e', '', '', '', '', 'uk', '992b0de6-8fa4-402d-83be-7c997a5ae30f', 'published'),
    ('ya-iotated', 'Ꙗ', 33, 'Я', 'Йотированное А', 'Древняя буква Ꙗ передавала звук я и позже стала одной из основ современного знака Я.', NULL, 'Я', '#9a2b1e', '', '', '', '', 'ru', '992b0de6-8fa4-402d-83be-7c997a5ae30f', 'published'),
    ('ya-iotated', 'Ꙗ', 33, 'Я', 'Iotated A', 'Я is a sign of the Old Slavonic alphabet. Its meaning: Iotated A. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Я', '#9a2b1e', '', '', '', '', 'en', '992b0de6-8fa4-402d-83be-7c997a5ae30f', 'published'),
    ('ye', 'Ѥ', 34, 'Е йотированное', 'Йотоване Е', 'Е йотированное — знак старословʼянської азбуки. Його сенс: Йотоване Е. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ЙЕ', '#1f3f66', '', '', '', '', 'uk', 'd494123a-25e5-4520-bc0f-11d3d6abd4d0', 'published'),
    ('ye', 'Ѥ', 34, 'Е йотированное', 'Йотированное Е', 'Ѥ помогала передавать начальное или мягкое йотированное звучание е в древних текстах.', NULL, 'ЙЕ', '#1f3f66', '', '', '', '', 'ru', 'd494123a-25e5-4520-bc0f-11d3d6abd4d0', 'published'),
    ('ye', 'Ѥ', 34, 'Е йотированное', 'Iotated E', 'Е йотированное is a sign of the Old Slavonic alphabet. Its meaning: Iotated E. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ЙЕ', '#1f3f66', '', '', '', '', 'en', 'd494123a-25e5-4520-bc0f-11d3d6abd4d0', 'published'),
    ('yu', 'Ю', 35, 'Ю', 'Йотоване У', 'Ю — знак старословʼянської азбуки. Його сенс: Йотоване У. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ю', '#9a2b1e', '', '', '', '', 'uk', 'fa46c5cf-509d-4ff6-9f3b-12b695fa826a', 'published'),
    ('yu', 'Ю', 35, 'Ю', 'Йотированное У', 'Ю соединяет мягкость и полноту звучания, завершая ряд букв, близких современному читателю.', NULL, 'Ю', '#9a2b1e', '', '', '', '', 'ru', 'fa46c5cf-509d-4ff6-9f3b-12b695fa826a', 'published'),
    ('yu', 'Ю', 35, 'Ю', 'Iotated U', 'Ю is a sign of the Old Slavonic alphabet. Its meaning: Iotated U. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ю', '#9a2b1e', '', '', '', '', 'en', 'fa46c5cf-509d-4ff6-9f3b-12b695fa826a', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('big-yus', 'Ѫ', 36, 'Юс большой', 'Великий носовий голосний', 'Юс большой — знак старословʼянської азбуки. Його сенс: Великий носовий голосний. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'О носовое', '#1f3f66', '', '', '', '', 'uk', '419d93fa-be34-4f1d-b3ec-94629a2c6a57', 'published'),
    ('big-yus', 'Ѫ', 36, 'Юс большой', 'Большой носовой гласный', 'Большой юс сохранял древний носовой звук, который позднее исчез из большинства славянских языков.', NULL, 'О носовое', '#1f3f66', '', '', '', '', 'ru', '419d93fa-be34-4f1d-b3ec-94629a2c6a57', 'published'),
    ('big-yus', 'Ѫ', 36, 'Юс большой', 'Large nasal vowel', 'Юс большой is a sign of the Old Slavonic alphabet. Its meaning: Large nasal vowel. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'О носовое', '#1f3f66', '', '', '', '', 'en', '419d93fa-be34-4f1d-b3ec-94629a2c6a57', 'published'),
    ('iotated-big-yus', 'Ѭ', 37, 'Юс большой йотированный', 'Йотований великий юс', 'Юс большой йотированный — знак старословʼянської азбуки. Його сенс: Йотований великий юс. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ЙО носовое', '#9a2b1e', '', '', '', '', 'uk', '2ff6bc14-4762-4721-adb5-9ddf636d5cef', 'published'),
    ('iotated-big-yus', 'Ѭ', 37, 'Юс большой йотированный', 'Йотированный большой юс', 'Ѭ соединял йотацию и носовой гласный, показывая богатство древней славянской фонетики.', NULL, 'ЙО носовое', '#9a2b1e', '', '', '', '', 'ru', '2ff6bc14-4762-4721-adb5-9ddf636d5cef', 'published'),
    ('iotated-big-yus', 'Ѭ', 37, 'Юс большой йотированный', 'Iotated large yus', 'Юс большой йотированный is a sign of the Old Slavonic alphabet. Its meaning: Iotated large yus. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ЙО носовое', '#9a2b1e', '', '', '', '', 'en', '2ff6bc14-4762-4721-adb5-9ddf636d5cef', 'published'),
    ('little-yus', 'Ѧ', 38, 'Юс малый', 'Малий носовий голосний', 'Юс малый — знак старословʼянської азбуки. Його сенс: Малий носовий голосний. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Е носовое', '#1f3f66', '', '', '', '', 'uk', '26ebe828-1b83-4522-a759-2c23bc1ef622', 'published'),
    ('little-yus', 'Ѧ', 38, 'Юс малый', 'Малый носовой гласный', 'Малый юс передавал другой носовой звук и помогает увидеть, насколько тонкой была старая письменность.', NULL, 'Е носовое', '#1f3f66', '', '', '', '', 'ru', '26ebe828-1b83-4522-a759-2c23bc1ef622', 'published'),
    ('little-yus', 'Ѧ', 38, 'Юс малый', 'Small nasal vowel', 'Юс малый is a sign of the Old Slavonic alphabet. Its meaning: Small nasal vowel. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Е носовое', '#1f3f66', '', '', '', '', 'en', '26ebe828-1b83-4522-a759-2c23bc1ef622', 'published'),
    ('iotated-little-yus', 'Ѩ', 39, 'Юс малый йотированный', 'Йотований малий юс', 'Юс малый йотированный — знак старословʼянської азбуки. Його сенс: Йотований малий юс. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ЙЕ носовое', '#9a2b1e', '', '', '', '', 'uk', 'cb1bc6b7-d792-46b0-aebf-648d981c3bea', 'published'),
    ('iotated-little-yus', 'Ѩ', 39, 'Юс малый йотированный', 'Йотированный малый юс', 'Ѩ употреблялся в некоторых традициях и показывает, что состав азбуки менялся по времени и регионам.', NULL, 'ЙЕ носовое', '#9a2b1e', '', '', '', '', 'ru', 'cb1bc6b7-d792-46b0-aebf-648d981c3bea', 'published'),
    ('iotated-little-yus', 'Ѩ', 39, 'Юс малый йотированный', 'Iotated small yus', 'Юс малый йотированный is a sign of the Old Slavonic alphabet. Its meaning: Iotated small yus. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ЙЕ носовое', '#9a2b1e', '', '', '', '', 'en', 'cb1bc6b7-d792-46b0-aebf-648d981c3bea', 'published'),
    ('ksi', 'Ѯ', 40, 'Кси', 'Грецька літера ксі', 'Кси — знак старословʼянської азбуки. Його сенс: Грецька літера ксі. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'КС', '#1f3f66', '', '', '', '', 'uk', '591b33c8-6cca-42b7-a46f-68c67a6d689b', 'published'),
    ('ksi', 'Ѯ', 40, 'Кси', 'Греческая буква кси', 'Кси использовалась главным образом в греческих заимствованиях и как числовой знак церковной письменности.', NULL, 'КС', '#1f3f66', '', '', '', '', 'ru', '591b33c8-6cca-42b7-a46f-68c67a6d689b', 'published'),
    ('ksi', 'Ѯ', 40, 'Кси', 'Greek letter xi', 'Кси is a sign of the Old Slavonic alphabet. Its meaning: Greek letter xi. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'КС', '#1f3f66', '', '', '', '', 'en', '591b33c8-6cca-42b7-a46f-68c67a6d689b', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('psi', 'Ѱ', 41, 'Пси', 'Грецька літера псі', 'Пси — знак старословʼянської азбуки. Його сенс: Грецька літера псі. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ПС', '#9a2b1e', '', '', '', '', 'uk', 'f25bcdf3-d900-412b-9a72-4fe5699b7740', 'published'),
    ('psi', 'Ѱ', 41, 'Пси', 'Греческая буква пси', 'Пси пришла из греческого письма и встречалась в церковных словах, именах и числовой записи.', NULL, 'ПС', '#9a2b1e', '', '', '', '', 'ru', 'f25bcdf3-d900-412b-9a72-4fe5699b7740', 'published'),
    ('psi', 'Ѱ', 41, 'Пси', 'Greek letter psi', 'Пси is a sign of the Old Slavonic alphabet. Its meaning: Greek letter psi. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ПС', '#9a2b1e', '', '', '', '', 'en', 'f25bcdf3-d900-412b-9a72-4fe5699b7740', 'published'),
    ('fita', 'Ѳ', 42, 'Фита', 'Грецька theta', 'Фита — знак старословʼянської азбуки. Його сенс: Грецька theta. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Ф / Т', '#1f3f66', '', '', '', '', 'uk', '99969d7e-a287-4843-9bff-8ba4b6edced8', 'published'),
    ('fita', 'Ѳ', 42, 'Фита', 'Греческая theta', 'Фита передавала греческую theta и в славянском чтении часто сближалась с ф или т.', NULL, 'Ф / Т', '#1f3f66', '', '', '', '', 'ru', '99969d7e-a287-4843-9bff-8ba4b6edced8', 'published'),
    ('fita', 'Ѳ', 42, 'Фита', 'Greek theta', 'Фита is a sign of the Old Slavonic alphabet. Its meaning: Greek theta. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Ф / Т', '#1f3f66', '', '', '', '', 'en', '99969d7e-a287-4843-9bff-8ba4b6edced8', 'published'),
    ('izhitsa', 'Ѵ', 43, 'Ижица', 'Грецька upsilon', 'Ижица — знак старословʼянської азбуки. Його сенс: Грецька upsilon. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'И / В / Ю', '#9a2b1e', '', '', '', '', 'uk', '0a091e42-8e2e-4aac-83c9-33ca0eb9172f', 'published'),
    ('izhitsa', 'Ѵ', 43, 'Ижица', 'Греческая upsilon', 'Ижица связана с греческой традицией, встречалась в книжных словах и имела числовое значение.', NULL, 'И / В / Ю', '#9a2b1e', '', '', '', '', 'ru', '0a091e42-8e2e-4aac-83c9-33ca0eb9172f', 'published'),
    ('izhitsa', 'Ѵ', 43, 'Ижица', 'Greek upsilon', 'Ижица is a sign of the Old Slavonic alphabet. Its meaning: Greek upsilon. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'И / В / Ю', '#9a2b1e', '', '', '', '', 'en', '0a091e42-8e2e-4aac-83c9-33ca0eb9172f', 'published'),
    ('koppa', 'Ҁ', 44, 'Коппа', 'Коппа, числовий знак', 'Коппа — знак старословʼянської азбуки. Його сенс: Коппа, числовий знак. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'Числовой знак', '#1f3f66', '', '', '', '', 'uk', '53594344-56d4-463f-ae60-7fa9226633e7', 'published'),
    ('koppa', 'Ҁ', 44, 'Коппа', 'Коппа, знак числа', 'Коппа почти не имела звуковой роли и главным образом служила числовым знаком в ранней кириллице.', NULL, 'Числовой знак', '#1f3f66', '', '', '', '', 'ru', '53594344-56d4-463f-ae60-7fa9226633e7', 'published'),
    ('koppa', 'Ҁ', 44, 'Коппа', 'Koppa, a numeral sign', 'Коппа is a sign of the Old Slavonic alphabet. Its meaning: Koppa, a numeral sign. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'Числовой знак', '#1f3f66', '', '', '', '', 'en', '53594344-56d4-463f-ae60-7fa9226633e7', 'published'),
    ('ot', 'Ѿ', 45, 'От', 'Лігатура омега + твердо', 'От — знак старословʼянської азбуки. Його сенс: Лігатура омега + твердо. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ОТ', '#9a2b1e', '', '', '', '', 'uk', 'ca7ee72d-7304-47fd-835a-7c8c53df8387', 'published'),
    ('ot', 'Ѿ', 45, 'От', 'Лигатура омега + твердо', 'Ѿ появилась как книжная лигатура для от и часто воспринимается как отдельный знак в расширенных азбучных таблицах.', NULL, 'ОТ', '#9a2b1e', '', '', '', '', 'ru', 'ca7ee72d-7304-47fd-835a-7c8c53df8387', 'published'),
    ('ot', 'Ѿ', 45, 'От', 'Ligature omega + tverdo', 'От is a sign of the Old Slavonic alphabet. Its meaning: Ligature omega + tverdo. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ОТ', '#9a2b1e', '', '', '', '', 'en', 'ca7ee72d-7304-47fd-835a-7c8c53df8387', 'published')
ON CONFLICT (slug, language) DO NOTHING;

INSERT INTO church_alphabet_letters
    (slug, letter, sort_order, name, short_description, full_text, numeric_value,
     modern_equivalent, color, card_image_url, main_image_url, seo_title, seo_description,
     language, translation_group_id, status)
VALUES
    ('djerv', 'Ꙉ', 46, 'Дервь', 'Регіональний знак південнословʼянської традиції', 'Дервь — знак старословʼянської азбуки. Його сенс: Регіональний знак південнословʼянської традиції. Такі літери зберігали звук, числову памʼять і книжну традицію давнього церковного письма.', NULL, 'ДЖ / Ђ', '#1f3f66', '', '', '', '', 'uk', 'bf76dcb8-0de8-48b3-9292-dda7e2d907f6', 'published'),
    ('djerv', 'Ꙉ', 46, 'Дервь', 'Региональный знак южнославянской традиции', 'Дервь встречался в ранних сербских памятниках; это региональный знак, поэтому именно он делает расширенный набор вариативным.', NULL, 'ДЖ / Ђ', '#1f3f66', '', '', '', '', 'ru', 'bf76dcb8-0de8-48b3-9292-dda7e2d907f6', 'published'),
    ('djerv', 'Ꙉ', 46, 'Дервь', 'Regional sign of the South Slavic tradition', 'Дервь is a sign of the Old Slavonic alphabet. Its meaning: Regional sign of the South Slavic tradition. These letters preserved sound, numerical memory, and the book tradition of early church writing.', NULL, 'ДЖ / Ђ', '#1f3f66', '', '', '', '', 'en', 'bf76dcb8-0de8-48b3-9292-dda7e2d907f6', 'published')
ON CONFLICT (slug, language) DO NOTHING;
