export const CATALOG = {
  calendar: {
    path: "calendar-days",
    required: ["title", "slug", "dateNewStyle", "language"],
    text: ["description", "history"],
    image: "imageUrl",
    strings: [
      "dateOldStyle",
      "dateNewStyle",
      "calendarType",
      "title",
      "slug",
      "language",
      "dayType",
      "description",
      "history",
      "imageUrl",
      "seoTitle",
      "seoDescription",
    ],
    numbers: ["rank"],
    refs: {},
  },
  saints: {
    path: "saints",
    required: ["name", "slug", "language"],
    text: ["shortDescription", "biography"],
    image: "imageUrl",
    strings: [
      "slug",
      "name",
      "shortDescription",
      "biography",
      "feastDayOldStyle",
      "feastDayNewStyle",
      "imageUrl",
      "language",
    ],
    refs: {
      iconId: "icons",
      calendarDayId: "calendar",
    },
  },
  icons: {
    path: "icons",
    required: ["title", "slug", "language"],
    text: ["description"],
    image: "imageUrl",
    strings: [
      "title",
      "slug",
      "imageUrl",
      "saintName",
      "feastName",
      "description",
      "language",
    ],
    arrays: ["galleryUrls"],
    refs: {
      calendarDayId: "calendar",
    },
  },
  prayers: {
    path: "prayers",
    required: ["title", "slug", "language", "text"],
    text: ["text"],
    image: "imageUrl",
    strings: [
      "slug",
      "title",
      "text",
      "audioUrl",
      "imageUrl",
      "source",
      "sourceUrl",
      "note",
      "language",
      "prayerType",
    ],
    refs: {
      iconId: "icons",
      calendarDayId: "calendar",
    },
  },
  articles: {
    path: "articles",
    required: ["title", "slug", "language", "content"],
    text: ["content"],
    strings: [
      "title",
      "slug",
      "content",
      "language",
      "seoTitle",
      "seoDescription",
    ],
    refs: {
      iconId: "icons",
      calendarDayId: "calendar",
    },
  },
  gospel: {
    path: "gospel",
    required: ["title", "slug", "language", "reference", "text"],
    text: ["text", "explanation"],
    strings: ["slug", "title", "reference", "text", "explanation", "language"],
    refs: {
      iconId: "icons",
      calendarDayId: "calendar",
    },
  },
  alphabet: {
    path: "alphabet",
    required: ["letter", "name", "slug", "language"],
    text: ["shortDescription", "fullText"],
    image: "mainImageUrl",
    strings: [
      "slug",
      "letter",
      "name",
      "shortDescription",
      "fullText",
      "modernEquivalent",
      "cardImageUrl",
      "mainImageUrl",
      "seoTitle",
      "seoDescription",
      "audioUrl",
      "language",
    ],
    numbers: ["sortOrder", "numericValue"],
    refs: {},
  },
} as const;
