#!/usr/bin/env node
/**
 * Generates an idempotent, additive-only SQL seed file for the 30-day
 * Julian-calendar content population task (civil 2026-09-01..2026-09-30 /
 * old-style 2026-08-19..2026-09-17). Safe to run this generator (and the
 * resulting SQL) more than once: every INSERT is guarded by
 * `WHERE NOT EXISTS (...)` keyed on the same lookup the app itself uses
 * (church_calendar_days.date_old_style, then calendar_day_id + language
 * [+ prayer_type] for the per-type tables) -- a second run touches zero
 * rows. No DELETE/DROP/UPDATE anywhere in this file's output.
 *
 * Usage: node scripts/calendar-seed/generate-sql.mjs > scripts/calendar-seed/seed.sql
 * Then:  wrangler d1 execute svetikony-production --remote --file=scripts/calendar-seed/seed.sql
 */
import { randomUUID } from 'node:crypto';
import { DAYS } from './data.mjs';

function sqlString(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Real, cited canonical/fixed Orthodox prayer excerpts -- see the task's
 * own instruction that morning/evening prayer does NOT need 30 unique
 * "official" texts, just a safe, verified pool reused across days. Every
 * `text` below is either universally fixed liturgical wording or a
 * directly-fetched excerpt (see `source`/`sourceUrl`), never AI-composed
 * prose presented as canonical. */
const MORNING_PRAYERS = [
  {
    title: 'Молитва Оптинських старців (на початок дня)',
    text: 'Господи, дай мені з душевним спокоєм зустріти все, що принесе мені цей день. Дай мені цілком віддатися волі Твоїй святій.',
    source: 'Молитва Оптинських старців',
    sourceUrl: 'https://gumoreska.in.ua/molytva-optynskyh-startsiv/',
  },
  {
    title: 'Царю Небесний (молитва Святому Духові)',
    text: 'Царю Небесний, Утішителю, Душе істини, що всюди єси і все наповняєш, Скарбе добра і життя Подателю, прийди і вселися в нас, і очисти нас від усякої скверни, і спаси, Благий, душі наші.',
    source: 'Молитвослов, фіксована літургійна молитва',
    sourceUrl: '',
  },
  {
    title: 'Отче наш (Молитва Господня)',
    text: 'Отче наш, що єси на небесах, нехай святиться ім’я Твоє, нехай прийде Царство Твоє, нехай буде воля Твоя, як на небі, так і на землі. Хліб наш насущний дай нам сьогодні, і прости нам провини наші, як і ми прощаємо винуватцям нашим, і не введи нас у випробування, але визволи нас від лукавого.',
    source: 'Євангеліє від Матвія 6:9-13',
    sourceUrl: '',
  },
  {
    title: 'Трисвяте',
    text: 'Святий Боже, Святий Кріпкий, Святий Безсмертний, помилуй нас. Слава Отцю, і Сину, і Святому Духові, і нині, і повсякчас, і на віки віків. Амінь.',
    source: 'Молитвослов, фіксована літургійна молитва',
    sourceUrl: '',
  },
];

const EVENING_PRAYERS = [
  {
    title: 'Псалом 90',
    text: 'Хто живе під охороною Всевишнього, той під покровом Бога Небесного оселиться. Каже він до Господа: «Ти пристановище і захист мій, Бог мій, і я уповаю на Тебе». Він спасе тебе від сіті ловця і від пошести згубної.',
    source: 'Псалтир, Псалом 90',
    sourceUrl: 'https://olha-maria.com.ua/dukhovne-zbahachennia/molytvy-ukrainskoiu/psalom-90',
  },
  {
    title: 'Нині відпускаєш (пісня Симеона Богоприїмця)',
    text: 'Нині відпускаєш раба Твого, Владико, за словом Твоїм, з миром, бо побачили очі мої спасіння Твоє, яке приготував Ти перед лицем усіх народів, світло на просвіту поганам і на славу народу Твого Ізраїля.',
    source: 'Євангеліє від Луки 2:29-32',
    sourceUrl: '',
  },
  {
    title: 'Молитва до Ангела Хоронителя',
    text: 'Ангеле Христів, хоронителю мій святий, життя моє огороджуй, розум мій просвіщай і серце моє направляй, і на всякий добрий путь наставляй мене, і від усякого зла бережи, щоб я через тебе прославляв Бога повсякчас. Амінь.',
    source: 'Молитвослов, вечірні молитви',
    sourceUrl: '',
  },
  {
    title: 'Достойно є',
    text: 'Достойно є воістину величати Тебе, Богородицю, Тебе, що вічно блаженна і пренепорочна, і Матір Бога нашого. Чеснішу від херувимів і незрівнянно славнішу від серафимів, що без зотління Бога Слово породила, Тебе, воістину Богородицю, величаємо.',
    source: 'Молитвослов, богородична пісня',
    sourceUrl: '',
  },
];

const lines = [];
function emit(sql) {
  lines.push(sql.trim() + ';');
}

lines.push('-- Auto-generated by scripts/calendar-seed/generate-sql.mjs -- DO NOT hand-edit.');
lines.push('-- Idempotent additive seed: civil 2026-09-01..2026-09-30 / old-style 2026-08-19..2026-09-17.');
lines.push('');

for (const [index, day] of DAYS.entries()) {
  lines.push(`-- ==== ${day.civilDate} (old-style ${day.oldStyle}) ====`);

  if (!day.existingCalendarDayId) {
    const calendarId = randomUUID();
    emit(`
      INSERT INTO church_calendar_days
        (id, date_old_style, date_new_style, calendar_type, title, slug, language, day_type, description, status)
      SELECT ${sqlString(calendarId)}, ${sqlString(day.oldStyle)}, ${sqlString(day.civilDate)}, 'both',
        ${sqlString(day.calendarTitle)}, ${sqlString(`${day.oldStyle}-${calendarId.slice(0, 8)}`)}, 'uk',
        ${sqlString(day.dayType)}, ${sqlString(day.calendarDescription)}, 'published'
      WHERE NOT EXISTS (SELECT 1 FROM church_calendar_days WHERE date_old_style = ${sqlString(day.oldStyle)})
    `);
  }

  const calendarDaySubquery = `(SELECT id FROM church_calendar_days WHERE date_old_style = ${sqlString(day.oldStyle)})`;

  if (day.saint) {
    const saintId = randomUUID();
    emit(`
      INSERT INTO church_saints
        (id, calendar_day_id, slug, name, short_description, biography, language, status)
      SELECT ${sqlString(saintId)}, ${calendarDaySubquery}, ${sqlString(`${day.oldStyle}-${saintId.slice(0, 8)}`)},
        ${sqlString(day.saint.name)}, ${sqlString(day.saint.shortDescription)}, ${sqlString(day.saint.biography)}, 'uk', 'published'
      WHERE NOT EXISTS (
        SELECT 1 FROM church_saints WHERE calendar_day_id = ${calendarDaySubquery} AND language = 'uk'
      )
    `);
  }

  if (day.gospel) {
    const gospelId = randomUUID();
    emit(`
      INSERT INTO church_gospel_readings
        (id, calendar_day_id, slug, title, reference, text, explanation, language, status)
      SELECT ${sqlString(gospelId)}, ${calendarDaySubquery}, ${sqlString(`${day.oldStyle}-${gospelId.slice(0, 8)}`)},
        ${sqlString(day.gospel.title)}, ${sqlString(day.gospel.reference)}, '', ${sqlString(day.gospel.explanation)}, 'uk', 'published'
      WHERE NOT EXISTS (
        SELECT 1 FROM church_gospel_readings WHERE calendar_day_id = ${calendarDaySubquery} AND language = 'uk'
      )
    `);
  }

  if (day.faithStory) {
    const articleId = randomUUID();
    emit(`
      INSERT INTO church_articles
        (id, calendar_day_id, title, slug, content, language, status)
      SELECT ${sqlString(articleId)}, ${calendarDaySubquery}, ${sqlString(day.faithStory.title)},
        ${sqlString(`${day.oldStyle}-${articleId.slice(0, 8)}`)}, ${sqlString(day.faithStory.content)}, 'uk', 'published'
      WHERE NOT EXISTS (
        SELECT 1 FROM church_articles WHERE calendar_day_id = ${calendarDaySubquery} AND language = 'uk'
      )
    `);
  }

  const morning = MORNING_PRAYERS[index % MORNING_PRAYERS.length];
  const morningId = randomUUID();
  emit(`
    INSERT INTO church_prayers
      (id, calendar_day_id, slug, title, text, source, source_url, language, prayer_type, status)
    SELECT ${sqlString(morningId)}, ${calendarDaySubquery}, ${sqlString(`${day.oldStyle}-morning-${morningId.slice(0, 8)}`)},
      ${sqlString(morning.title)}, ${sqlString(morning.text)}, ${sqlString(morning.source)}, ${sqlString(morning.sourceUrl)},
      'uk', 'morning', 'published'
    WHERE NOT EXISTS (
      SELECT 1 FROM church_prayers WHERE calendar_day_id = ${calendarDaySubquery} AND language = 'uk' AND prayer_type = 'morning'
    )
  `);

  const evening = EVENING_PRAYERS[index % EVENING_PRAYERS.length];
  const eveningId = randomUUID();
  emit(`
    INSERT INTO church_prayers
      (id, calendar_day_id, slug, title, text, source, source_url, language, prayer_type, status)
    SELECT ${sqlString(eveningId)}, ${calendarDaySubquery}, ${sqlString(`${day.oldStyle}-evening-${eveningId.slice(0, 8)}`)},
      ${sqlString(evening.title)}, ${sqlString(evening.text)}, ${sqlString(evening.source)}, ${sqlString(evening.sourceUrl)},
      'uk', 'evening', 'published'
    WHERE NOT EXISTS (
      SELECT 1 FROM church_prayers WHERE calendar_day_id = ${calendarDaySubquery} AND language = 'uk' AND prayer_type = 'evening'
    )
  `);

  lines.push('');
}

process.stdout.write(lines.join('\n') + '\n');
