export const calendarCopy={
  uk:{tagline:'Віра. Історія. Світ.',globe:'Глобус',calendar:'Календар',saints:'Святі',churches:'Храми',history:'Історія',map:'Карта',orthodox:'Православний календар',today:'Сьогодні',previous:'Попередній день',next:'Наступний день',date:'Дата',close:'Закрити',menu:'Навігація',day:'Пам’яті дня',count:'пам’ятей',saint:'Святі',feast:'Свята',icon:'Ікони',event:'Події',all:'Усі',places:'Пов’язані місця',noPlace:'Місце не вказано',loading:'Завантаження…',error:'Не вдалося завантажити',retry:'Спробувати ще',life:'Житіє',prayer:'Молитва',more:'Докладніше',sources:'Джерела',showAll:'Показати все',north:'На північ',zoomIn:'Наблизити',zoomOut:'Віддалити',sun:'Сонячне освітлення',search:'Пошук у пам’ятях дня',empty:'Записів не знайдено',birth:'Народження',death:'Смерть',burial:'Поховання',residence:'Проживання',machine:'Місце потребує історичної перевірки',shop:'Магазин'},
  ru:{tagline:'Вера. История. Мир.',globe:'Глобус',calendar:'Календарь',saints:'Святые',churches:'Храмы',history:'История',map:'Карта',orthodox:'Православный календарь',today:'Сегодня',previous:'Предыдущий день',next:'Следующий день',date:'Дата',close:'Закрыть',menu:'Навигация',day:'Памяти дня',count:'памятей',saint:'Святые',feast:'Праздники',icon:'Иконы',event:'События',all:'Все',places:'Связанные места',noPlace:'Место не указано',loading:'Загрузка…',error:'Не удалось загрузить',retry:'Повторить',life:'Житие',prayer:'Молитва',more:'Подробнее',sources:'Источники',showAll:'Показать всё',north:'На север',zoomIn:'Приблизить',zoomOut:'Отдалить',sun:'Солнечное освещение',search:'Поиск в памятях дня',empty:'Записи не найдены',birth:'Рождение',death:'Смерть',burial:'Погребение',residence:'Проживание',machine:'Место требует исторической проверки',shop:'Магазин'},
  en:{tagline:'Faith. History. World.',globe:'Globe',calendar:'Calendar',saints:'Saints',churches:'Churches',history:'History',map:'Map',orthodox:'Orthodox calendar',today:'Today',previous:'Previous day',next:'Next day',date:'Date',close:'Close',menu:'Navigation',day:'Day commemorations',count:'commemorations',saint:'Saints',feast:'Feasts',icon:'Icons',event:'Events',all:'All',places:'Related places',noPlace:'Place not specified',loading:'Loading…',error:'Could not load',retry:'Try again',life:'Life',prayer:'Prayer',more:'Read more',sources:'Sources',showAll:'Show all',north:'North up',zoomIn:'Zoom in',zoomOut:'Zoom out',sun:'Sun lighting',search:'Search day commemorations',empty:'No entries found',birth:'Birth',death:'Death',burial:'Burial',residence:'Residence',machine:'Location needs historical verification',shop:'Shop'}
};

/** calendar_geo_places.place_type (migrations/0026_calendar_geo.sql CHECK
 * constraint) -> localized label, used by the mobile SacredPlacePanel's
 * collapsed "name/type/photo" preview (ТЗ п.17). Not reused for anything
 * else -- the desktop panel never shows a bare type label. */
export const placeTypeCopy={
  uk:{city:'Місто',village:'Село',church:'Храм',monastery:'Монастир',shrine:'Святиня',birthplace:'Місце народження',martyrdom_place:'Місце мучеництва',burial_place:'Місце поховання',relic_location:'Місце зберігання мощей',historical_region:'Історична область',pilgrimage_place:'Місце паломництва',other:'Святе місце'},
  ru:{city:'Город',village:'Село',church:'Храм',monastery:'Монастырь',shrine:'Святыня',birthplace:'Место рождения',martyrdom_place:'Место мученичества',burial_place:'Место погребения',relic_location:'Место хранения мощей',historical_region:'Историческая область',pilgrimage_place:'Место паломничества',other:'Святое место'},
  en:{city:'City',village:'Village',church:'Church',monastery:'Monastery',shrine:'Shrine',birthplace:'Birthplace',martyrdom_place:'Place of martyrdom',burial_place:'Burial place',relic_location:'Relic location',historical_region:'Historical region',pilgrimage_place:'Pilgrimage site',other:'Sacred place'}
};

/** SacredPlacePanel-only copy (GlobeShell pilot) -- kept separate from
 * calendarCopy above instead of growing that object further; the panel
 * merges both dictionaries by locale. */
export const sacredPlaceCopy={
  uk:{about:'Про місце',collection:'Колекція',history:'Історія',directions:'Як дістатися',buy:'Купити',emptyCollection:'Колекція для цієї святині поки готується',stockAvailable:'В наявності',stockMadeToOrder:'Під замовлення',stockUnavailable:'Немає в наявності',website:'Офіційний сайт',map:'Показати на карті',hours:'Години роботи',noProfile:'Опис цього місця уточнюється',address:'Адреса',primaryBadge:'Головна пам’ятка',partOf:'У складі',complexObjects:'Об’єкти комплексу',favorite:'Додати в обране',collectionHeading:'Колекція святині',collectionSubheading:'Картки собору та пов’язаних святих',productLabel:'Колекційна картка',browseCards:'Листати картки',coordinates:'Координати',buildRoute:'Побудувати маршрут',routeSoon:'Прокладання маршруту зʼявиться незабаром',relatedSaints:'Пов’язані святі',relatedArticles:'Пов’язані статті',relatedEvents:'Пов’язані події',noRelated:'Поки що немає пов’язаних матеріалів',expand:'Розгорнути',collapse:'Згорнути'},
  ru:{about:'О месте',collection:'Коллекция',history:'История',directions:'Как добраться',buy:'Купить',emptyCollection:'Коллекция для этой святыни пока готовится',stockAvailable:'В наличии',stockMadeToOrder:'Под заказ',stockUnavailable:'Нет в наличии',website:'Официальный сайт',map:'Показать на карте',hours:'Часы работы',noProfile:'Описание этого места уточняется',address:'Адрес',primaryBadge:'Главная реликвия',partOf:'В составе',complexObjects:'Объекты комплекса',favorite:'Добавить в избранное',collectionHeading:'Коллекция святыни',collectionSubheading:'Карточки собора и связанных святых',productLabel:'Коллекционная карточка',browseCards:'Листать карточки',coordinates:'Координаты',buildRoute:'Построить маршрут',routeSoon:'Прокладка маршрута появится в ближайшее время',relatedSaints:'Связанные святые',relatedArticles:'Связанные статьи',relatedEvents:'Связанные события',noRelated:'Пока нет связанных материалов',expand:'Развернуть',collapse:'Свернуть'},
  en:{about:'About',collection:'Collection',history:'History',directions:'Getting there',buy:'Buy',emptyCollection:'The collection for this shrine is being prepared',stockAvailable:'In stock',stockMadeToOrder:'Made to order',stockUnavailable:'Unavailable',website:'Official website',map:'Show on map',hours:'Opening hours',noProfile:'A description of this place is coming soon',address:'Address',primaryBadge:'Featured item',partOf:'Part of',complexObjects:'Objects in the complex',favorite:'Add to favorites',collectionHeading:'Shrine collection',collectionSubheading:'Cards of the cathedral and related saints',productLabel:'Collectible card',browseCards:'Browse cards',coordinates:'Coordinates',buildRoute:'Build a route',routeSoon:'Turn-by-turn directions are coming soon',relatedSaints:'Related saints',relatedArticles:'Related articles',relatedEvents:'Related events',noRelated:'No related content yet',expand:'Expand',collapse:'Collapse'}
};

/** SacredPlotPanel-only copy (Sacred Plots pilot, Kyiv-Pechersk Lavra) --
 * kept separate from sacredPlaceCopy above since a Plot and a Place are
 * different selection concepts with their own panel. */
export const sacredPlotCopy={
  uk:{title:'Sacred Plot',relatedTo:'Пов’язано з',area:'Площа',status:'Статус',owner:'Власник',price:'Ціна',buy:'Купити',offer:'Пропозиція',details:'Деталі',
    statusAvailable:'Вільний',statusOwned:'Продано',statusReserved:'Заброньовано',noOwner:'—',
    disclaimer:'Цифрова територія. Не є правом власності на фізичну землю.',
    layerToggle:'Sacred Plots',availableOnly:'Лише доступні',buySoon:'Купівля з’явиться незабаром'},
  ru:{title:'Sacred Plot',relatedTo:'Связано с',area:'Площадь',status:'Статус',owner:'Владелец',price:'Цена',buy:'Купить',offer:'Предложение',details:'Детали',
    statusAvailable:'Свободен',statusOwned:'Продан',statusReserved:'Забронирован',noOwner:'—',
    disclaimer:'Цифровая территория. Не является правом собственности на физическую землю.',
    layerToggle:'Sacred Plots',availableOnly:'Только доступные',buySoon:'Покупка появится в ближайшее время'},
  en:{title:'Sacred Plot',relatedTo:'Related to',area:'Area',status:'Status',owner:'Owner',price:'Price',buy:'Buy',offer:'Make an offer',details:'Details',
    statusAvailable:'Available',statusOwned:'Owned',statusReserved:'Reserved',noOwner:'—',
    disclaimer:'Digital territory. Not a claim of ownership over physical land.',
    layerToggle:'Sacred Plots',availableOnly:'Available only',buySoon:'Purchasing is coming soon'},
};
