import { afterEach,describe,expect,it,vi } from 'vitest';
import * as THREE from 'three';
import { fixture } from '../terrain/test-support';
import { TerrainSelector,terrainTileBounds,neighborIds } from './terrain-selection';
import { terrainRootMatrix,terrainPoint } from './terrain-alignment';
import { projectTerrainPoint,bakeTerrainGeometry } from './terrain-projection';
import { latLngToVector3 } from './geography';
import type { LoadedManifest } from './terrain-loader';
const io=vi.hoisted(()=>({fetch:vi.fn(),decode:vi.fn(),dispose:vi.fn()}));
vi.mock('./terrain-loader',()=>({fetchTerrainTileBytes:io.fetch,decodeTerrainTile:io.decode,disposeTerrainObject:io.dispose}));
import { TerrainByteCache,TerrainStream } from './terrain-stream';
afterEach(()=>{vi.clearAllMocks();});
async function region(){const {manifest}=await fixture();manifest.bounds={minLon:20,minLat:41,maxLon:44,maxLat:53};manifest.grid={...manifest.grid,countX:3,countY:3};manifest.coordinateSystem={...(manifest.coordinateSystem as object),origin:{latitude:48.5,longitude:31}};const template=manifest.tiles[0];manifest.tiles=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)manifest.tiles.push({...template,x,y,tile_id:`l1_${x}_${y}`,file:`${x}_${y}.glb`,min_lat:49-y*4,max_lat:53-y*4,min_lon:20+x*8,max_lon:28+x*8,height_min:0,height_max:2000,vertex_resolution:[2,2]});return{...manifest,sourceUrl:'http://localhost:3000/terrain/test/L1/manifest.json'} as LoadedManifest;}
function camera(lat:number,lon:number,distance=1.92){const c=new THREE.PerspectiveCamera(45,1,0.001,100);c.position.copy(latLngToVector3(lat,lon,distance));c.lookAt(0,0,0);c.updateMatrixWorld();return c;}
function root(m:LoadedManifest){const g=new THREE.Group();g.matrix.copy(terrainRootMatrix(m,1.8,new THREE.Vector3()));g.matrixAutoUpdate=false;new THREE.Scene().add(g);return g;}
function selector(m:LoadedManifest,mobile=false){return new TerrainSelector(m.tiles.map(tile=>({tile,localBox:terrainTileBounds(m,tile),worldBox:new THREE.Box3(),sphere:new THREE.Sphere(),score:0})),1.8,mobile);}
describe('camera selection',()=>{
 it('selects a subset close to west and does not evaluate an idle camera again',async()=>{const m=await region(),s=selector(m),r=root(m),c=camera(50,24);const a=s.select(c,r,true,0)!;expect(a.visible.size).toBeGreaterThan(0);expect(a.visible.size).toBeLessThan(9);expect(s.select(c,r,true,1000)).toBeNull();expect(s.evaluations).toBe(1);c.zoom=2;c.updateProjectionMatrix();expect(s.select(c,r,true,2000)).not.toBeNull();expect(s.evaluations).toBe(2);});
 it('rejects the far hemisphere and separates distant preload from rendering',async()=>{const m=await region(),s=selector(m),r=root(m);expect(s.select(camera(-48,-149,3),r,true,0)!.visible.size,JSON.stringify(s.volumes.map(v=>({center:v.sphere.center.toArray(),radius:v.sphere.radius})))).toBe(0);const near=s.select(camera(48,31,6.3),r,true,1000)!;expect(near.visible.size).toBe(0);expect(near.preload.size).toBeGreaterThan(0);const far=s.select(camera(48,31,12),r,true,2000)!;expect(far.preload.size).toBe(0);expect(far.veryFar).toBe(true);});
 it('limits mobile visibility and only preloads immediate neighbors',async()=>{const m=await region(),s=selector(m,true),r=root(m);const a=s.select(camera(48,31,3),r,true,0)!;expect(a.visible.size).toBeLessThanOrEqual(4);expect(a.preload.size-a.visible.size).toBeLessThanOrEqual(1);const ids=neighborIds(m.tiles,new Set(['l1_1_1']),4);expect([...ids].sort()).toEqual(['l1_0_1','l1_1_0','l1_1_2','l1_2_1']);});
 it('conservative bounds contain projected height samples and the CPU bake is one-time',async()=>{const m=await region(),t=m.tiles[0],b=terrainTileBounds(m,t);for(let y=0;y<=20;y++)for(let x=0;x<=20;x++){const p=projectTerrainPoint(terrainPoint(m,t.min_lat+(t.max_lat-t.min_lat)*y/20,t.min_lon+(t.max_lon-t.min_lon)*x/20,2000),63.71);expect(b.containsPoint(p)).toBe(true);}
 const geo=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute([1,0,2,2,0,3,2,0,2],3));const group=new THREE.Group();group.add(new THREE.Mesh(geo,new THREE.MeshBasicMaterial()));bakeTerrainGeometry(group,m);const first=Array.from(geo.getAttribute('position').array);bakeTerrainGeometry(group,m);expect(Array.from(geo.getAttribute('position').array)).toEqual(first);expect(geo.boundingSphere!.radius).toBeGreaterThan(0);});
});
describe('separate network and GPU caches',()=>{
 it('deduplicates simultaneous fetches and validates cache TTL/budget eviction',async()=>{const m=await region(),cache=new TerrainByteCache({byteBudget:20,byteRetentionMs:1000});io.fetch.mockResolvedValue(new ArrayBuffer(12));const signal=new AbortController().signal;await Promise.all([cache.get(m.tiles[0],m,signal),cache.get(m.tiles[0],m,signal)]);expect(io.fetch).toHaveBeenCalledOnce();await cache.get(m.tiles[1],m,signal);expect(cache.bytes).toBe(12);await cache.get(m.tiles[1],m,signal);expect(cache.hits).toBe(1);cache.prune(performance.now()+1001);expect(cache.bytes).toBe(0);});
 it('does not expose LOADING meshes before preparation and retains bytes after GPU release',async()=>{const m=await region();io.fetch.mockResolvedValue(new ArrayBuffer(12));io.decode.mockImplementation(async(_bytes,t)=>{const g=new THREE.Group();g.name=t.tile_id;return g;});let finish!:()=>void;const prepared=new Promise<void>(r=>{finish=r;});const stream=new TerrainStream(m,1.8,false,()=>prepared);stream.root.matrix.copy(root(m).matrix);stream.root.matrixAutoUpdate=false;new THREE.Scene().add(stream.root);const c=camera(50,24);stream.update(c,true,0,1,0.05);await vi.waitFor(()=>expect(io.decode).toHaveBeenCalled());stream.update(c,true,200,1,0.05);expect(stream.entries.some(e=>e.state==='LOADING')).toBe(true);expect(stream.stats.visible).toBe(0);finish();await vi.waitFor(()=>expect(stream.entries.some(e=>e.state==='READY')).toBe(true));
 stream.update(c,false,1000,0,1);stream.update(c,false,47000,0,1);expect(stream.stats.loaded).toBe(0);expect(stream.cache.bytes).toBeGreaterThan(0);const requests=stream.cache.requests;stream.update(c,true,48000,1,0.05);await vi.waitFor(()=>expect(stream.entries.some(e=>e.state==='READY')).toBe(true));expect(stream.cache.requests).toBe(requests);expect(stream.cache.hits).toBeGreaterThan(0);stream.dispose();});
 it('keeps a cached tile while briefly turned away and never double-decodes an in-flight tile',async()=>{const m=await region();io.fetch.mockResolvedValue(new ArrayBuffer(12));io.decode.mockImplementation(async(_bytes,t)=>{const g=new THREE.Group();g.name=t.tile_id;return g;});const stream=new TerrainStream(m,1.8,true,async()=>{});stream.root.matrix.copy(root(m).matrix);stream.root.matrixAutoUpdate=false;new THREE.Scene().add(stream.root);const c=camera(50,24);for(let i=0;i<5;i++)stream.update(c,true,i*150,1,0.05);await vi.waitFor(()=>expect(stream.entries.some(e=>e.state==='READY')).toBe(true));expect(io.decode).toHaveBeenCalledOnce();stream.update(c,false,1000,0,1);expect(stream.stats.cached).toBeGreaterThan(0);stream.update(c,false,3000,0,1);expect(io.dispose).not.toHaveBeenCalled();stream.dispose();});
 it('records a failed tile without silently retrying each frame',async()=>{const m=await region();io.fetch.mockRejectedValue(new Error('offline'));vi.spyOn(console,'warn').mockImplementation(()=>{});const stream=new TerrainStream(m,1.8,true,async()=>{});stream.root.matrix.copy(root(m).matrix);stream.root.matrixAutoUpdate=false;new THREE.Scene().add(stream.root);const c=camera(50,24);stream.update(c,true,0,1,0.1);await vi.waitFor(()=>expect(stream.failure).toBe(true));expect(stream.failed.length).toBe(1);const id=stream.failed[0];for(let i=1;i<5;i++)stream.update(c,true,i*150,1,0.1);expect(stream.entries.find(e=>e.tile.tile_id===id)!.state).toBe('FAILED');stream.dispose();vi.restoreAllMocks();});
});
