import {execFileSync} from 'node:child_process';
import {expect,it} from 'vitest';
it('applies confirmed identity, manual provenance, rejection, stale guards and lossless merge transactionally',()=>{
 const result=execFileSync(process.execPath,['--input-type=module','-e',`
 import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
 import {planCalendarReview,placeRevision} from './lib/church/geo-review-plan.ts';
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;CREATE TABLE church_calendar_days(id TEXT PRIMARY KEY)');
 for(const name of ['0026_calendar_geo','0027_calendar_geo_identity','0028_calendar_geo_workflow','0029_calendar_geo_review_guard','0030_calendar_geo_revision'])db.exec(readFileSync('migrations/'+name+'.sql','utf8'));
 db.prepare('INSERT INTO calendar_geo_profiles(id,profile_json,updated_at) VALUES (?,?,?)').run('p',JSON.stringify({names:['Test']}),'v1');
 db.exec("INSERT INTO calendar_geo_profile_candidates(profile_id,qid,confidence,evidence_json) VALUES ('p','Q42','HIGH','{}')");
 const snapshot=()=>{const profile=db.prepare('SELECT * FROM calendar_geo_profiles WHERE id=?').get('p');return {profile,databaseRevision:db.prepare('SELECT revision FROM calendar_geo_revision WHERE id=1').get().revision,entity:profile.entity_id?db.prepare('SELECT * FROM calendar_geo_entities WHERE id=?').get(profile.entity_id):null,candidate:db.prepare('SELECT * FROM calendar_geo_profile_candidates WHERE profile_id=? AND qid=?').get('p','Q42')}};
 const apply=(command,extra={})=>{const s={...snapshot(),...extra};const c={profileId:'p',revision:s.profile.updated_at,...command};const plan=planCalendarReview(s,c,'editor','v'+command.requestId);db.exec('BEGIN');try{for(const item of plan)db.prepare(item.sql).run(...item.params);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e;}};
 apply({requestId:'2',action:'confirm',qid:'Q42',entityType:'saint'});
 assert.equal(snapshot().entity.match_status,'reviewed_verified');assert.equal(snapshot().entity.geo_status,'unknown');
 assert.equal(snapshot().candidate.confidence,'HIGH');assert.equal(db.prepare('SELECT count(*) n FROM calendar_geo_review_log').get().n,1);
 db.exec("INSERT INTO calendar_geo_profile_candidates(profile_id,qid,confidence,evidence_json) VALUES ('p','Q43','LOW','{}')");
 apply({requestId:'alternative',action:'reject',qid:'Q43'},{candidate:db.prepare("SELECT * FROM calendar_geo_profile_candidates WHERE qid='Q43'").get()});
 assert.equal(snapshot().profile.match_status,'reviewed_verified');assert.equal(snapshot().entity.wikidata_id,'Q42');
 assert.equal(db.prepare("SELECT status FROM calendar_geo_profile_candidates WHERE qid='Q43'").get().status,'rejected');
 assert.throws(()=>apply({requestId:'3',action:'manual_place',name:'Test',lat:20,lon:30,relationType:'birth',geoStatus:'reviewed_verified'}),/Source/);
 apply({requestId:'4',action:'manual_place',name:'Place',lat:20,lon:30,relationType:'birth',geoStatus:'reviewed_verified',sourceUrl:'https://example.org/source',sourceNote:'Verified coordinates'});
 assert.equal(db.prepare('SELECT count(*) n FROM calendar_geo_provenance WHERE place_id IS NOT NULL').get().n,1);
 const place=db.prepare("SELECT * FROM calendar_geo_places WHERE id='manual:4'").get();
 assert.throws(()=>apply({requestId:'edit-stale',action:'edit_place',placeId:place.id,placeRevision:'old',name:'Edited',lat:21,lon:31,relationType:'birth',geoStatus:'manual_unverified'},{place}),/Stale place/);
 apply({requestId:'edit',action:'edit_place',placeId:place.id,placeRevision:placeRevision(place),name:'Edited',lat:21,lon:31,originalRelationType:'birth',relationType:'residence',geoStatus:'manual_unverified'},{place});
 assert.equal(db.prepare('SELECT lat FROM calendar_geo_places WHERE id=?').get(place.id).lat,21);
 assert.equal(db.prepare("SELECT match_status FROM calendar_geo_relations WHERE relation_type='birth'").get().match_status,'reviewed_rejected');
 assert.equal(db.prepare("SELECT count(*) n FROM calendar_geo_relations WHERE match_status!='reviewed_rejected'").get().n,1);
 const revisionSnapshot=snapshot();const revisionPlan=planCalendarReview(revisionSnapshot,{requestId:'revision-stale',profileId:'p',revision:revisionSnapshot.profile.updated_at,action:'geo_unknown'},'editor','later');
 db.exec("UPDATE calendar_geo_places SET lon=32 WHERE id='manual:4'");
 db.exec('BEGIN');assert.throws(()=>{for(const item of revisionPlan)db.prepare(item.sql).run(...item.params)},/CHECK/);db.exec('ROLLBACK');
 assert.equal(db.prepare("SELECT count(*) n FROM calendar_geo_review_log WHERE id='revision-stale'").get().n,0);
 apply({requestId:'5',action:'remove_relation',placeId:'manual:4',relationType:'birth'});
 assert.equal(db.prepare('SELECT match_status FROM calendar_geo_relations').get().match_status,'reviewed_rejected');
 assert.throws(()=>apply({requestId:'6',revision:'v1',action:'reject',qid:'Q42'}),/Stale/);
 const stale=snapshot();const plan=planCalendarReview(stale,{requestId:'stale',profileId:'p',revision:stale.profile.updated_at,action:'reject',qid:'Q42'},'editor','later');
 db.exec("UPDATE calendar_geo_profiles SET updated_at='concurrent' WHERE id='p'");
 db.exec('BEGIN');assert.throws(()=>{for(const item of plan)db.prepare(item.sql).run(...item.params)});db.exec('ROLLBACK');assert.equal(snapshot().candidate.status,'confirmed');
 db.exec("INSERT INTO calendar_geo_entities(id,entity_type,canonical_name) VALUES ('target','saint','Target')");
 db.exec("INSERT INTO calendar_geo_content_links(entity_id,content_type,translation_group_id) VALUES ('wd:Q42','prayer','prayer-group')");
 apply({requestId:'7',action:'merge',targetEntityId:'target'},{target:db.prepare("SELECT * FROM calendar_geo_entities WHERE id='target'").get()});
 assert.equal(snapshot().profile.entity_id,'target');assert.equal(db.prepare("SELECT wikidata_id FROM calendar_geo_entities WHERE id='target'").get().wikidata_id,'Q42');
 assert.equal(db.prepare("SELECT count(*) n FROM calendar_geo_content_links WHERE entity_id='target'").get().n,1);
 assert.equal(db.prepare("SELECT count(*) n FROM calendar_geo_relations WHERE entity_id='target'").get().n,2);
 assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);
 db.exec("INSERT INTO calendar_geo_profiles(id,entity_id,profile_json,updated_at) VALUES ('shared','target','{}','v1')");
 apply({requestId:'8',action:'reject',qid:'Q42'},{otherProfiles:1});assert.equal(snapshot().candidate.status,'rejected');
 assert.equal(snapshot().profile.entity_id,null);assert.equal(db.prepare("SELECT wikidata_id FROM calendar_geo_entities WHERE id='target'").get().wikidata_id,'Q42');
 console.log('PASS');
 `],{encoding:'utf8'});expect(result.trim()).toBe('PASS');
});
