import {describe,it,expect,vi,afterEach} from 'vitest';
import {TerrainStorage,terrainHash} from './storage';
import {requireTerrainLocal} from './http';
import {parseTerrainManifest} from './contract';
import {fixture} from './test-support';
afterEach(()=>vi.unstubAllEnvs());
describe('LOCAL terrain storage',()=>{
 it('stages manifest, hides incomplete bundle, verifies each tile, registers complete metadata',async()=>{const s=await fixture();const start=await s.storage.begin('test',1,s.manifest);expect(start.complete).toBe(false);await expect(s.storage.file('test',1,'manifest.json')).rejects.toThrow();const id=start.bundleId!;await s.storage.tile('test',1,'0_0',id,s.bytes,'model/gltf-binary');const result=await s.storage.reconcile('test',1,id);expect(result.complete).toBe(true);expect(result.objects).toHaveLength(2);expect((await s.storage.file('test',1,'manifest.json')).expected.mimeType).toBe('application/json');});
 it('conditional writes make resume idempotent and never overwrite',async()=>{const s=await fixture();const start=await s.storage.begin('test',1,s.manifest);await s.storage.tile('test',1,'0_0',start.bundleId!,s.bytes,'model/gltf-binary');const count=s.puts.length;await s.storage.begin('test',1,s.manifest);await s.storage.tile('test',1,'0_0',start.bundleId!,s.bytes,'model/gltf-binary');expect(s.puts.length).toBe(count);});
 it('a conflicting bundle cannot replace any original bytes',async()=>{const s=await fixture();await s.storage.begin('test',1,s.manifest);const changed={...s.manifest,loading:'different'};await expect(s.storage.begin('test',1,changed)).rejects.toMatchObject({status:409,details:expect.stringMatching(/different immutable/)});expect(s.puts).toHaveLength(2);});
 it('fails MIME, hash, unauthorized tile and bundle ID before put',async()=>{const s=await fixture();const start=await s.storage.begin('test',1,s.manifest);const count=s.puts.length;await expect(s.storage.tile('test',1,'0_0',start.bundleId!,s.bytes,'image/png')).rejects.toThrow();await expect(s.storage.tile('test',1,'1_1',start.bundleId!,s.bytes,'model/gltf-binary')).rejects.toThrow();await expect(s.storage.tile('test',1,'0_0','0'.repeat(64),s.bytes,'model/gltf-binary')).rejects.toThrow();const broken=s.bytes.slice(0);new Uint8Array(broken)[20]=33;await expect(s.storage.tile('test',1,'0_0',start.bundleId!,broken,'model/gltf-binary')).rejects.toThrow();expect(s.puts.length).toBe(count);});
 it('reconcile catches corruption and unexpected objects even after completion',async()=>{const s=await fixture();const start=await s.storage.begin('test',1,s.manifest);await s.storage.tile('test',1,'0_0',start.bundleId!,s.bytes,'model/gltf-binary');await s.storage.reconcile('test',1,start.bundleId!);s.data.get('terrain/test/L1/0_0.glb')!.bytes=new ArrayBuffer(s.bytes.byteLength);const result=await s.storage.status('test',1);expect(result.complete).toBe(false);expect(result.state).toBe('conflict');await expect(s.storage.file('test',1,'0_0.glb')).rejects.toMatchObject({status:409,details:expect.stringMatching(/integrity/)});});
 it('rejects unowned prefixes and concurrent reservation conflicts',async()=>{const s=await fixture();s.data.set('terrain/test/L1/other.glb',{bytes:s.bytes,mime:'model/gltf-binary',etag:'a'});await expect(s.storage.begin('test',1,s.manifest)).rejects.toMatchObject({status:409,details:expect.stringMatching(/Unowned/)});expect(s.puts.length).toBe(0);});
 it('production builds reject even localhost; local runtime rejects production host',()=>{vi.stubEnv('NODE_ENV','production');expect(()=>requireTerrainLocal(new Request('http://localhost/api/admin/terrain-bundles/test/L1'))).toThrow('Authorization failed');vi.stubEnv('NODE_ENV','development');expect(()=>requireTerrainLocal(new Request('https://svetikony.com/api/admin/terrain-bundles/test/L1'))).toThrow();expect(()=>requireTerrainLocal(new Request('http://localhost/api/admin/terrain-bundles/test/L1'))).not.toThrow();});
});
